low:
    - rule:
        cwe_ids:
            - "523"
            - "522"
        id: express_default_cookie_config
        description: Cookies with default config detected.
        documentation_url: https://docs.bearer.com/reference/rules/express_default_cookie_config
      line_number: 8
      filename: default_session_config.js
      parent_line_number: 8
      parent_content: |-
        {
        			domain: "example.com",
        			secure: true,
        			httpOnly: false,
        			maxAge: 24 * 60 * 60 * 1000,
        			path: "/some-path"
        		}
    - rule:
        cwe_ids:
            - "523"
            - "522"
        id: express_default_session_config
        description: Session cookie with default config detected.
        documentation_url: https://docs.bearer.com/reference/rules/express_default_session_config
      line_number: 6
      filename: default_session_config.js
      parent_line_number: 6
      parent_content: |-
        {
            name: "my-custom-session-name",
        		cookie: {
        			domain: "example.com",
        			secure: true,
        			httpOnly: false,
        			maxAge: 24 * 60 * 60 * 1000,
        			path: "/some-path"
        		},
        	}


