type: "risk"
patterns:
  - |
    logger.info(<$ARGUMENT>)
  - |
    Rails.logger.info(<$ARGUMENT>)
  - |
    Sentry::Breadcrumb.new(<$ARGUMENT>)
  - |
    Sentry.init do |config|
      config.before_breadcrumb = lambda do |breadcrumb, hint|
        breadcrumb.message = $ANYTHING
        breadcrumb
      end
    end
  - |
    Sentry.set_user(<$ARGUMENT>)
languages:
  - ruby
id: "detect_ruby_logger"
type: "risk"
trigger: "local"
severity:
  - default: "low"
  - PII: "critical"
  - PHI: "medium"
  - PD: "high"
exclude_data_types: ["Unique Identifier"]
metadata:
  - failure_message: "failure message DSW-001"
  - description: "description DSW-001"
  - remediation_message: "remediation message DSW-001"
  - dsw_id: "DSW-001"
