version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    labels:
      - "echoes/intent: risk-mitigation"
  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    labels:
      - "echoes/intent: risk-mitigation"