patterns:
  - pattern: |
      res.write($<EXPRESS_REQ>)
    filters:
      - variable: EXPRESS_REQ
        detection: javascript_express_cross_site_scripting_request_obj
  - pattern: |
      res.send($<EXPRESS_REQ>)
    filters:
      - variable: EXPRESS_REQ
        detection: javascript_express_cross_site_scripting_request_obj
auxiliary:
  - id: javascript_express_cross_site_scripting_request_obj
    patterns:
      - req.$<_>
languages:
  - javascript
trigger: presence
severity:
  default: low
metadata:
  description: "Cross-site scripting (XSS) vulnerability detected."
  remediation_message: |
    ## Description
    TODO
  cwe_id:
    - 79
  id: "javascript_express_cross_site_scripting"
