patterns:
  - pattern: |
      res.write($<USER_INPUT>)
    filters:
      - variable: USER_INPUT
        detection: javascript_express_cross_site_scripting_request_obj
      - not:
          variable: USER_INPUT
          detection: javascript_express_cross_site_scripting_string_interpolation
  - pattern: |
      res.send($<USER_INPUT>)
    filters:
      - variable: USER_INPUT
        detection: javascript_express_cross_site_scripting_request_obj
      - not:
          variable: USER_INPUT
          detection: javascript_express_cross_site_scripting_string_interpolation
languages:
  - javascript
auxiliary:
  - id: javascript_express_cross_site_scripting_request_obj
    patterns:
      - req.params
      - req.query
      - req.body
      - req.cookies
      - req.headers
  - id: javascript_express_cross_site_scripting_string_interpolation
    patterns:
      - pattern: |
          { $<...>$<_>: $<USER_INPUT>$<...> }
        filters:
          - variable: USER_INPUT
            detection: javascript_express_cross_site_scripting_request_obj
trigger: presence
severity: high
metadata:
  description: "Cross-site scripting (XSS) vulnerability detected."
  remediation_message: |
    ## Description
    Sending unsanitized user input in a response puts your application at risk of cross-site scripting attacks.
    <!--
    ## Remediations
    Coming soon.
    ## Resources
    Coming soon.
    -->
  cwe_id:
    - 79
  id: "javascript_express_cross_site_scripting"
