patterns:
  - pattern: |
      eval($<USER_INPUT>)
    filters:
      - variable: USER_INPUT
        detection: javascript_express_eval_user_input_user_input
  - pattern: |
      new Function($<USER_INPUT>)
    filters:
      - variable: USER_INPUT
        detection: javascript_express_eval_user_input_user_input
  - pattern: |
      setTimeout($<USER_INPUT>)
    filters:
      - variable: USER_INPUT
        detection: javascript_express_eval_user_input_user_input
  - pattern: |
      setInterval($<USER_INPUT>)
    filters:
      - variable: USER_INPUT
        detection: javascript_express_eval_user_input_user_input
  - pattern: |
      vm.$<METHOD>($<...>$<USER_INPUT>$<...>)
    filters:
      - variable: METHOD
        values:
          - createContext
          - runInContext
          - runInNewContext
          - runInThisContext
          - compileFunction
      - variable: USER_INPUT
        detection: javascript_express_eval_user_input_user_input
  - pattern: |
      new vm.Script($<...>$<USER_INPUT>$<...>)
    filters:
      - variable: USER_INPUT
        detection: javascript_express_eval_user_input_user_input
auxiliary:
  - id: javascript_express_eval_user_input_user_input
    patterns:
      - req.params
      - req.query
      - req.body
      - req.cookies
      - req.headers
      - location
languages:
  - javascript
trigger: presence
severity: high
metadata:
  description: "Dangerous use of eval with user input detected"
  remediation_message: |
    ## Description

    Using eval with user input is dangerous. It can lead to remote code execution.

    <!--
    ## Resources
    Coming soon.
    -->
  cwe_id:
    - 94
    - 95
  id: "javascript_express_eval_user_input"
