patterns:
  - pattern: |
      require($<USER_INPUT>)
    filters:
      - variable: USER_INPUT
        detection: javascript_express_external_resource_req_object
  - pattern: |
      res.render($<USER_INPUT>$<...>)
    filters:
      - variable: USER_INPUT
        detection: javascript_express_external_resource_req_object
languages:
  - javascript
auxiliary:
  - id: javascript_express_external_resource_req_object
    patterns:
      - req.params
      - req.query
      - req.body
      - req.cookies
      - req.headers
trigger: presence
severity:
  default: "low"
metadata:
  description: "Rendering of resources resolved from external name or reference detected."
  remediation_message: |
    ## Description
    Coming soon.
    <!--
    ## Remediations
    Coming soon.
    ## Resources
    Coming soon.
    -->
  cwe_id:
    - 706
  id: "javascript_express_external_resource"
