patterns:
  - pattern: |
      require($<USER_INPUT>)
    filters:
      - variable: USER_INPUT
        detection: javascript_express_external_resource_req_object
  - pattern: |
      res.render($<USER_INPUT>$<...>)
    filters:
      - variable: USER_INPUT
        detection: javascript_express_external_resource_req_object
languages:
  - javascript
auxiliary:
  - id: javascript_express_external_resource_req_object
    patterns:
      - req.params
      - req.query
      - req.body
      - req.cookies
      - req.headers
trigger: presence
metadata:
  description: "Rendering of resources resolved from external name or reference detected."
  remediation_message: |
    ## Description
    Using raw unsanitized input when rendering resources is bad practice.

    ## Remediations
    ❌ Avoid passing user or request input to res.render() or require().

    ✅ Sanitize the input or use a safelist
    Where it is unavoidable to rely on user input, sanitize the input or use a safelist to keep the rendered resources within the expected scope.

    ```javascript
    var path = req.body.path
    if (['users', 'posts', 'pages'].includes(path)) {
      return res.render(`${path}/success`)
    }
    ```
  cwe_id:
    - 706
  id: "javascript_express_external_resource"
