patterns:
  - pattern: |
      $<MODULE>($<HARDCODED_SECRET_IN_HASH>)
    filters:
      - variable: MODULE
        values:
          - jwt
          - expressjwt
          - session
      - variable: HARDCODED_SECRET_IN_HASH
        detection: javascript_express_hardcoded_secret_in_hash
languages:
  - javascript
auxiliary:
  - id: javascript_express_hardcoded_secret_in_hash
    patterns:
      - pattern: |
          { secret: $<STRING_LITERAL> }
        filters:
          - variable: STRING_LITERAL
            detection: string_literal
            contains: false
trigger: presence
severity: high
metadata:
  description: "Hard-coded secret detected."
  remediation_message: |
    ## Description
    Code is not a secure place to store hard-coded secrets. Use environment variables instead.

    ## Remediations
    ✅ Use environment variables and a secret management system instead

    ```javascript
     app.use(
      session({
        secret: process.env.secret,
        name: "my-custom-session-name",
      })
    )
    ```

    ## Resources
    - [OWASP hardcoded passwords](https://owasp.org/www-community/vulnerabilities/Use_of_hard-coded_password)
  cwe_id:
    - 798
  id: "javascript_express_hardcoded_secret"
