patterns:
  - pattern: |
      $<MODULE>($<HARDCODED_SECRET_IN_HASH>)
    filters:
      - variable: MODULE
        values:
          - jwt
          - expressjwt
          - session
      - variable: HARDCODED_SECRET_IN_HASH
        detection: javascript_express_hardcoded_secret_in_hash
languages:
  - javascript
auxiliary:
  - id: javascript_express_hardcoded_secret_in_hash
    patterns:
      - pattern: |
          { secret: $<STRING_LITERAL> }
        filters:
          - variable: STRING_LITERAL
            detection: string_literal
            contains: false
trigger: presence
severity:
  default: "medium"
metadata:
  description: "Hard-coded secret detected."
  remediation_message: |
      ## Description
      Code is not a secure place to store hard-coded secrets. Use an env variable instead.
      <!--
      ## Remediations
      Coming soon.
      ## Resources
      Coming soon.
      -->
  cwe_id:
    - 798
  id: "javascript_express_hardcoded_secret"
