patterns:
  - pattern: |
      $<EXPRESS>.use($<FUNCTION_CALL>)
    filters:
      - variable: EXPRESS
        detection: javascript_express_helmet_express_init
      - variable: FUNCTION_CALL
        detection: javascript_express_helmet_configuration
trigger_rule_on_presence_of: javascript_express_helmet_express_init
auxiliary:
  - id: javascript_express_helmet_express_init
    patterns:
      - express()
  - id: javascript_express_helmet_configuration
    patterns:
      - helmet()
      - helmet.$<_>()
languages:
  - javascript
trigger: absence
severity:
  default: "medium"
metadata:
  description: "Security misconfiguration detected."
  remediation_message: |
    ## Description

    Helmet can help protect your app from some well-known web vulnerabilities by setting HTTP headers appropriately.

    ## Resources

    - https://expressjs.com/en/advanced/best-practice-security.html

    <!--
    ## Remediations
    Coming soon.
    -->
  cwe_id:
    - 693
  id: javascript_express_helmet_missing
