patterns:
  - pattern: |
      https.createServer()
auxiliary:
  - id: javascript_express_https_protocol_missing_http_server
    patterns:
      - $<_>.createServer()
languages:
  - javascript
trigger:
  match_on: absence
  required_detection: javascript_express_https_protocol_missing_http_server
metadata:
  description: "Missing https protocol detected."
  remediation_message: |
    ## Description
    Use HTTPS wherever possible. HTTPS uses the TLS (Transport Layer Security) protocol to encrypt communication, making it more secure than HTTP.

    ## Remediations
    ✅ Use the `https` module when calling `createServer()`

    ```javascript
    var https = require('https');
    var express = require('express');
    var app = express();

    var httpsServer = https.createServer(app)
    httpsServer.listen(8080);
    ```

    ## Resources
    - [Express Security Best Practices: use TLS](https://expressjs.com/en/advanced/best-practice-security.html#use-tls)
  cwe_id:
    - 693
  id: javascript_express_https_protocol_missing
