patterns:
  - pattern: |
      {
        cookie: {
          $<!>secure: false
        }
      }
  - pattern: |
      {
        cookie: {
          $<!>httpOnly: true
        }
      }
  - pattern: |
      cookieSession({
        $<!>secure: false
      })
  - pattern: |
      cookieSession({
        $<!>httpOnly: true
      })
languages:
  - javascript
trigger: presence
metadata:
  description: "Missing secure options for cookie detected."
  remediation_message: |
    ## Description
    To make sure cookies don't open your application up to exploits or unauthorized access, make sure to set security options appropriately.

    ## Remediations
    ✅ Set cookie security values to use HTTP(S) instead of client-side javascript.
    ✅ Set `secure` values to `true` to force cookies to only send over HTTPS.

    ## Resources
    - [Express Security Best Practices](https://expressjs.com/en/advanced/best-practice-security.html#use-cookies-securely)
  cwe_id:
    - 1004
    - 614
  id: "express_insecure_cookie"
