patterns:
  - pattern: |
      $<MODULE>.precompile($<USER_INPUT>$<...>)
    filters:
      - variable: MODULE
        values:
          - Handlebars
          - handlebars
      - variable: USER_INPUT
        detection: javascript_express_insecure_template_rendering_req_object
  - pattern: |
      $<MODULE>.compile($<USER_INPUT>$<...>)
    filters:
      - variable: MODULE
        values:
          - pug
          - ejs
          - Handlebars
          - handlebars
          - Hogan
      - variable: USER_INPUT
        detection: javascript_express_insecure_template_rendering_req_object
  - pattern: |
      $<MODULE>.render($<USER_INPUT>$<...>)
    filters:
      - variable: MODULE
        values:
          - pug
          - ejs
          - eta
          - Eta
          - nunjucks
          - Mustache
          - Sqrl
          - whiskers
          - hbs
      - variable: USER_INPUT
        detection: javascript_express_insecure_template_rendering_req_object
  - pattern: |
      $<MODULE>.renderString($<USER_INPUT>$<...>)
    filters:
      - variable: MODULE
        values:
          - nunjucks
      - variable: USER_INPUT
        detection: javascript_express_insecure_template_rendering_req_object
  - pattern: |
      $<MODULE>.renderView($<USER_INPUT>$<...>)
    filters:
      - variable: MODULE
        values:
          - hbs
      - variable: USER_INPUT
        detection: javascript_express_insecure_template_rendering_req_object
  - pattern: |
      $<MODULE>.template($<USER_INPUT>$<...>)
    filters:
      - variable: MODULE
        values:
          - _
          - doT
      - variable: USER_INPUT
        detection: javascript_express_insecure_template_rendering_req_object
  - pattern: |
      $<LIQUID_INIT>.render($<USER_INPUT>$<...>)
    filters:
      - variable: LIQUID_INIT
        detection: javascript_express_insecure_template_rendering_liquid_init
      - variable: USER_INPUT
        detection: javascript_express_insecure_template_rendering_req_object
languages:
  - javascript
auxiliary:
  - id: javascript_express_insecure_template_rendering_req_object
    patterns:
      - req.params
      - req.query
      - req.body
      - req.cookies
      - req.headers
  - id: javascript_express_insecure_template_rendering_liquid_init
    patterns:
      - new Liquid()
trigger: presence
skip_data_types:
  - "Unique Identifier"
metadata:
  description: "Insecure template rendering detected."
  remediation_message: |
    ## Description
    Do not include externally influenced or user-given input data in rendered templates.

    <!--
    ## Remediations
    Coming soon.
    ## Resources
    Coming soon.
    -->
  cwe_id:
    - 1336
  id: "javascript_express_insecure_template_rendering"
