patterns:
  - pattern: |
      res.redirect($<EXPRESS_REQ>$<...>)
    filters:
      - variable: EXPRESS_REQ
        detection: javascript_express_open_redirect_request_obj
auxiliary:
  - id: javascript_express_open_redirect_request_obj
    patterns:
      - req.params.$<_>
      - req.query.$<_>
      - req.body.$<_>
      - req.cookies.$<_>
      - req.headers.$<_>
languages:
  - javascript
trigger: presence
severity:
  default: "low"
metadata:
  description: "Open redirect detected."
  remediation_message: |
    ## Description
    A redirect using unsanitized user input is bad practice and puts your application at greater risk of phishing attacks.
    <!--
    ## Remediations
    Coming soon.
    ## Resources
    Coming soon.
    -->
  cwe_id:
    - 601
  id: "javascript_express_open_redirect"
