patterns:
  - pattern: |
      path.$<METHOD>($<...>$<USER_INPUT>$<...>)
    filters:
      - variable: METHOD
        values:
          - join
          - resolve
      - variable: USER_INPUT
        detection: javascript_express_path_traversal_request_obj
auxiliary:
  - id: javascript_express_path_traversal_request_obj
    patterns:
      - req.params
      - req.query
      - req.body
      - req.cookies
      - req.headers
languages:
  - javascript
trigger: presence
severity:
  default: "warning"
metadata:
  description: "Possible path traversal vulnerability detected."
  remediation_message: |
    ## Description
    Allowing unsanitized user input in path resolution methods means an attacker could gain access to files and folders outside of the intended scope.
    <!--
    ## Remediations
    Coming soon.
    ## Resources
    Coming soon.
    -->
  cwe_id:
    - 22
  id: "javascript_express_path_traversal"
