patterns:
  - pattern: |
      $<EXPRESS>.disable($<POWERED_BY>)
    filters:
      - variable: EXPRESS
        detection: javascript_express_reduce_fingerprint_express_init
      - variable: POWERED_BY
        regex: (?i)['"]x-powered-by['"]
  - pattern: |
      $<EXPRESS>.use($<FUNCTION_CALL>)
    filters:
      - variable: EXPRESS
        detection: javascript_express_reduce_fingerprint_express_init
      - variable: FUNCTION_CALL
        detection: javascript_express_reduce_fingerprint_helmet_configuration
trigger_rule_on_presence_of: javascript_express_reduce_fingerprint_express_init
auxiliary:
  - id: javascript_express_reduce_fingerprint_express_init
    patterns:
      - express()
  - id: javascript_express_reduce_fingerprint_helmet_configuration
    patterns:
      - helmet.hidePoweredBy()
languages:
  - javascript
trigger: absence
severity:
  default: "medium"
metadata:
  description: "Security misconfiguration detected."
  remediation_message: |
    ## Description

    It can help to provide an extra layer of obsecurity to reduce server fingerprinting. Though not a security issue itself, a method to improve the overall posture of a web server is to take measures to reduce the ability to fingerprint the software being used on the server. Server software can be fingerprinted by kwirks in how they respond to specific requests.
    By default, Express.js sends the X-Powered-By response header banner. This can be disabled using the app.disable() method:

    ```
      app.disable('x-powered-by')
    ```

    ## Resources

    - https://expressjs.com/en/advanced/best-practice-security.html

    <!--
    ## Remediations
    Coming soon.
    -->
  cwe_id:
    - 693
  id: javascript_express_reduce_fingerprint
