patterns:
  - pattern: |
      $<SEQUELIZE>.query($<EXPRESS_REQ>)
    filters:
      - variable: SEQUELIZE
        detection: javascript_express_sql_injection_sequelize_init
      - variable: EXPRESS_REQ
        detection: javascript_express_sql_injection_request_obj
auxiliary:
  - id: javascript_express_sql_injection_request_obj
    patterns:
      - req.$<_>
  - id: javascript_express_sql_injection_sequelize_init
    patterns:
      - new Sequelize()
languages:
  - javascript
trigger: presence
severity:
  default: low
metadata:
  description: "SQL injection vulnerability detected."
  remediation_message: |
    ## Description
    TODO
  cwe_id:
    - 89
  id: "javascript_express_sql_injection"
