patterns:
  - pattern: |
      {
        $<SESSION>
        $<!>$<STATIC>
      }
    filters:
      - variable: SESSION
        detection: javascript_express_static_asset_with_session_session
      - variable: STATIC
        detection: javascript_express_static_asset_with_session_static
auxiliary:
  - id: javascript_express_static_asset_with_session_session
    patterns:
      - pattern: app.use($<MIDDLEWARE>)
        filters:
          - variable: MIDDLEWARE
            detection: javascript_express_static_asset_with_session_session_init
  - id: javascript_express_static_asset_with_session_session_init
    patterns:
      - session()
  - id: javascript_express_static_asset_with_session_static
    patterns:
      - pattern: app.use($<MIDDLEWARE>)
        filters:
          - variable: MIDDLEWARE
            detection: javascript_express_static_asset_with_session_static_init
  - id: javascript_express_static_asset_with_session_static_init
    patterns:
      - express.static()
languages:
  - javascript
trigger: presence
metadata:
  description: Static asset with active session detected.
  remediation_message: |
    ## Description
    Static assets are often cached by services in front of the application
    (eg. CDNs). Serving static assets with sessions enabled may lead to
    Cross-Site Request Forgery (CSRF) attacks that can hijack a user's session.

    ## Remediations

    ✅ Ensure static resources are handled prior to session initialization:

    ```javascript
      // static middleware should be added before session middleware
      app.use(express.static(__dirname + "/public"))

      app.use(session())
    ```
  cwe_id:
    - 352
    - 668
  id: javascript_express_static_asset_with_session
