patterns:
  - pattern: |
      $<LIB_METHOD>($<EXPRESS_REQ>)
    filters:
      - variable: LIB_METHOD
        values:
          - deserializeError
          - deserialize_error
      - either:
        - variable: EXPRESS_REQ
          detection: javascript_express_insecure_deserialization_request_obj
        - variable: EXPRESS_REQ
          detection: javascript_express_deserialization_buffer
  - pattern: |
      $<LIB>.unserialize($<EXPRESS_REQ>)
    filters:
      - variable: LIB
        values:
          - nodeSerialize
          - node_serialize
      - either:
        - variable: EXPRESS_REQ
          detection: javascript_express_insecure_deserialization_request_obj
        - variable: EXPRESS_REQ
          detection: javascript_express_deserialization_buffer
auxiliary:
  - id: javascript_express_insecure_deserialization_request_obj
    patterns:
      - req.$<_>
  - id: javascript_express_deserialization_buffer
    patterns:
      - Buffer.from(req.$<_>).toString()
languages:
  - javascript
trigger: presence
severity:
  default: "warning"
metadata:
  description: "Deserialization of untrusted data detected."
  remediation_message: |
    ## Description
    TODO
  cwe_id:
    - 502
  id: "javascript_express_unsafe_deserialization"
