patterns:
  - pattern: |
      $<LIB_METHOD>($<EXPRESS_REQ>)
    filters:
      - variable: LIB_METHOD
        values:
          - deserializeError
          - deserialize_error
      - either:
        - variable: EXPRESS_REQ
          detection: javascript_express_insecure_deserialization_request_obj
        - variable: EXPRESS_REQ
          detection: javascript_express_deserialization_buffer
  - pattern: |
      $<LIB>.unserialize($<EXPRESS_REQ>)
    filters:
      - variable: LIB
        values:
          - nodeSerialize
          - node_serialize
      - either:
        - variable: EXPRESS_REQ
          detection: javascript_express_insecure_deserialization_request_obj
        - variable: EXPRESS_REQ
          detection: javascript_express_deserialization_buffer
auxiliary:
  - id: javascript_express_insecure_deserialization_request_obj
    patterns:
      - req.params.$<_>
      - req.query.$<_>
      - req.body.$<_>
      - req.cookies.$<_>
      - req.headers.$<_>
  - id: javascript_express_deserialization_buffer
    patterns:
      - Buffer.from(req.$<_>).toString()
languages:
  - javascript
trigger: presence
severity:
  default: "warning"
metadata:
  description: "Deserialization of untrusted data detected."
  remediation_message: |
    ## Description
    It is bad practice to deserialize untrusted data, such as data direct from the request object.
    <!--
    ## Remediations
    Coming soon.
    ## Resources
    Coming soon.
    -->
  cwe_id:
    - 502
  id: "javascript_express_unsafe_deserialization"
