patterns:
  - pattern: |
      $<LIB_METHOD>($<USER_INPUT>)
    filters:
      - variable: LIB_METHOD
        values:
          - deserializeError
          - deserialize_error
      - either:
        - variable: USER_INPUT
          detection: javascript_express_insecure_deserialization_request_obj
        - variable: USER_INPUT
          detection: javascript_express_deserialization_buffer
  - pattern: |
      $<LIB>.unserialize($<USER_INPUT>)
    filters:
      - variable: LIB
        values:
          - nodeSerialize
          - node_serialize
      - either:
        - variable: USER_INPUT
          detection: javascript_express_insecure_deserialization_request_obj
        - variable: USER_INPUT
          detection: javascript_express_deserialization_buffer
auxiliary:
  - id: javascript_express_insecure_deserialization_request_obj
    patterns:
      - req.params
      - req.query
      - req.body
      - req.cookies
      - req.headers
  - id: javascript_express_deserialization_buffer
    patterns:
      - pattern: |
          Buffer.from($<USER_INPUT>).toString()
        filters:
          - variable: USER_INPUT
            detection: javascript_express_insecure_deserialization_request_obj
languages:
  - javascript
trigger: presence
severity: high
metadata:
  description: "Deserialization of untrusted data detected."
  remediation_message: |
    ## Description
    It is bad practice to deserialize (unmarshal) untrusted data, such as data direct from the request object.
    Attackers can transfer payloads or malicious code via serialized data, and deserializing such data puts your application at risk.

    ## Remediations
    ❌ Do not deserialize untrusted data
    ✅ Prefer pure (data-only) and language-agnostic (de)serialization formats such as JSON or XML
    Avoiding language-specific (de)serialization formats reduces the risk of attackers manipulating the deserialization process for malicious purposes.

    ```javascript
      JSON.parse(req.params)
    ```

    ## Resources
    - [OWASP Deserialization cheat sheet](https://cheatsheetseries.owasp.org/cheatsheets/Deserialization_Cheat_Sheet.html)
  cwe_id:
    - 502
  id: "javascript_express_unsafe_deserialization"
