patterns:
  - pattern: | # xml2js
      parseString($<EXPRESS_REQ>$<...>)
    filters:
      - variable: EXPRESS_REQ
        detection: javascript_express_xxe_vulnerability_request_obj
  - pattern: |
      $<XML2JS_PARSER>.$<METHOD>($<EXPRESS_REQ>$<...>)
    filters:
      - variable: XML2JS_PARSER
        detection: javascript_express_xxe_vulnerability_xml2js_parser
      - variable: EXPRESS_REQ
        detection: javascript_express_xxe_vulnerability_request_obj
      - variable: METHOD
        values:
          - parseString
          - parseStringPromise
  - pattern: |
      $<EXPAT_PARSER>.$<METHOD>($<EXPRESS_REQ>$<...>)
    filters:
      - variable: EXPAT_PARSER
        detection: javascript_express_xxe_vulnerability_node_expat_parser
      - variable: EXPRESS_REQ
        detection: javascript_express_xxe_vulnerability_request_obj
      - variable: METHOD
        values:
          - parse
          - write
  - pattern: |
      $<LIB_XML>.$<METHOD>(
        $<_>,
        {
          $<!>noent: true
        }
      )
    filters:
      - variable: LIB_XML
        values:
          - libxml
          - libxmljs
          - libxml2
          - libxml2js
      - variable: METHOD
        values:
          - parseXml
          - parseXmlString
  - pattern: | # xml2json
      parser.toXml($<EXPRESS_REQ>$<...>)
    filters:
      - variable: EXPRESS_REQ
        detection: javascript_express_xxe_vulnerability_request_obj
auxiliary:
  - id: javascript_express_xxe_vulnerability_request_obj
    patterns:
      - req.$<_>
  - id: javascript_express_xxe_vulnerability_node_expat_parser
    patterns:
      - new expat.Parser()
  - id: javascript_express_xxe_vulnerability_xml2js_parser
    patterns:
      - new xml2js.Parser()
languages:
  - javascript
trigger: presence
severity:
  default: "low"
metadata:
  description: "XML External Entity vulnerability detected."
  remediation_message: |
    ## Description
    Avoid parsing untrusted data as XML. Such data could include URIs that resolve to resources that are outside of the current context, leading to XML External Entity (XXE) injection.
    <!--
    ## Remediations
    Coming soon.
    ## Resources
    Coming soon.
    -->
  cwe_id:
    - 611
  id: "javascript_express_xxe_vulnerability"
