languages:
  - ruby
patterns:
  - pattern: |
      if request.get?
      else
      end
  - pattern: |
      unless request.get?
      end
  - pattern: |
      $<_> unless request.get?
trigger: presence
severity: medium
metadata:
  description: "Potential for HTTP verb confusion detected."
  remediation_message: |
    ## Description
    Rails uses the same actions for both GET and HEAD requests. When creating
    actions that handle both GET and state altering verbs (eg. POST), the use
    of `request.get?` can lead to unexpected state changes.

    ### Remediations

    ✅ Use separate action logic for GET and POST

    ✅ Check for state altering verbs rather than GET:

    ```ruby
    if request.post?
      alter_state
    end
    ```
  cwe_id:
    - 650
  id: ruby_rails_http_verb_confusion
