languages:
  - ruby
patterns:
  - pattern: |
      $<METHOD>($<ARGUMENT>: $<_>)
    filters:
      - variable: METHOD
        values:
          - skip_after_action
          - skip_around_action
          - skip_before_action
          - skip_after_filter
          - skip_around_filter
          - skip_before_filter
          - skip_filter
      - variable: ARGUMENT
        values:
          - except
          - unless
trigger: presence
metadata:
  description: "Insecure disabling of callback detected."
  remediation_message: |
    ## Description
    When using except/unless for disabling a callback, there is a high chance
    of skipping important access control logic by accident.

    ### Remediations

    ✅ Prefer enumerating all of the actions using `only`:

    ```ruby
    skip_before_action :access_control, only: %i[public_action1 public_action2]
    ```
  cwe_id:
    - 284
  id: ruby_rails_insecure_disabling_of_callback
