patterns:
  - |
    Rails.application.configure do
      $<!>config.force_ssl = false
    end
languages:
  - ruby
trigger: presence
severity:
  default: low # FIXME: warning
metadata:
  description: "Force all incoming communication through SSL."
  remediation_message: |
    ## Description
    When applications process sensitive data, they should default to always use SSL when available. This rule checks if force SSL is enabled at the application level.

    ### Remediations
    This helps avoid attacks like [session hijacking](https://guides.rubyonrails.org/security.html#session-hijacking). More importantly, unencrypted HTTP communication sends all requests as plain text, meaning anyone listening in can see all the traffic and extract user data.

    While you want to avoid sending sensitive data whenever possible, it's unavoidable so protecting the connection is an important method of improving your rails application data security.

    ✅ To force all traffic to your application to be encrypted though SSL, use the following Rails configuration option:

    ```ruby
    config.force_ssl = true
    ```

    ## Resources
    - [Configuring Rails Applications - Ruby on Rails Guides](https://guides.rubyonrails.org/configuring.html#config-force-ssl)
  dsr_id: DSR-2
  id: ruby_rails_insecure_communication
