type: "risk"
patterns:
  - |
    Rails.application.configure do
       config.force_ssl = false
       $<!>config.force_ssl = false
     end
languages:
  - ruby
trigger: "global"
severity:
  default: "critical"
omit_parent_content: true
metadata:
  description: "Force all incoming communication through SSL."
  remediation_message: ""
  dsr_id: "DSR-2"
