type: "risk"
patterns:
  - |
    Rails.application.configure do
      $<!>config.force_ssl = false
    end
languages:
  - ruby
trigger: "presence"
severity:
  default: "low" # FIXME: warning
omit_parent_content: true
metadata:
  description: "Force all incoming communication through SSL."
  remediation_message: ""
  dsr_id: "DSR-2"
  id: "ruby_rails_insecure_communication"
