type: "risk"
patterns:
  - |
    Net::FTP.new()
  - |
    Net::FTP.open()
  - pattern: |
      Net::FTP.open do
        $<DATA_TYPE>
      end
    filters:
      - variable: DATA_TYPE
        detection: datatype
languages:
  - ruby
trigger: "local"
severity:
  default: "low"
  PII: "critical"
  PHI: "medium"
  PD: "high"
metadata:
  description: "Only communicate using SFTP connections."
  remediation_message: ""
  dsr_id: "DSR-2"
