patterns:
  - |
    Rails.application.configure do
      config.action_mailer.smtp_settings = {
        $<!>openssl_verify_mode: OpenSSL::SSL::VERIFY_NONE
      }
    end
  - |
    Rails.application.configure do
      config.action_mailer.smtp_settings = {
        $<!>openssl_verify_mode: "none"
      }
    end
languages:
  - ruby
trigger: presence
severity:
  default: low
  PII: critical
  PHI: medium
  PD: high
metadata:
  description: "Only communicate with secure SMTP connections."
  remediation_message: |
    ## Description

    Secure connections using SMTP help prevent unauthorized actors from viewing transmitted data. This policy checks if SMTP mailer settings are set to only allow secure connections.

    ## Remediations
    ✅ When using the SMTP protocol, make sure to enable SSL encryption in ActionMailer configuration:

    ```ruby
    config.action_mailer.smtp_settings = {
    	...
    	ssl: true
    }
    ```
    <!--
    ## Resources
    Coming soon.
    -->
  dsr_id: DSR-2
  cwe_id:
    - 319
  id: ruby_rails_insecure_smtp
