patterns:
  - |
    class UsersController < ApplicationController
      http_basic_authenticate_with password: "$<!>$<$PASSWORD>"
    end
languages:
  - ruby
trigger: presence
metadata:
  description: "Insecure HTTP Password."
  remediation_message: |
    Coming soon
  id: ruby_rails_insecure_http_password
