type: "risk"
patterns:
  - |
    Net::FTP.open do
      $ANYTHING
    end
languages:
  - ruby
detect_presence: true
trigger: "local"
severity:
  default: "low"
  PII: "critical"
  PHI: "medium"
  PD: "high"
omit_parent_content: true
metadata:
  failure_message: "failure message DSW-006"
  description: "description DSW-006"
  remediation_message: "remediation message DSW-006"
  dsw_id: "DSW-006"
