type: "risk"
patterns:
  - |
    Net::FTP.new()
  - |
    Net::FTP.open()
  - |
    $<!>Net::FTP.open() do
      $<_>
    end
  - pattern: |
      Net::FTP.open() do
        $<DATA_TYPE>
      end
    filters:
      - variable: DATA_TYPE
        detection: datatype
languages:
  - ruby
trigger: "presence"
severity:
  default: "low" # FIXME: warning
  PII: "critical"
  PHI: "medium"
  PD: "high"
metadata:
  description: "Only communicate using SFTP connections."
  remediation_message: ""
  dsr_id: "DSR-2"
  id: "ruby_rails_insecure_ftp"
