type: "risk"
patterns:
  - |
    Rails.application.configure do
      config.action_mailer.smtp_settings = {
        $<!>openssl_verify_mode: OpenSSL::SSL::VERIFY_NONE
      }
    end
  - |
    Rails.application.configure do
      config.action_mailer.smtp_settings = {
        $<!>openssl_verify_mode: "none"
      }
    end
languages:
  - ruby
trigger: "presence"
severity:
  default: "low" # FIXME: warning
  PII: "critical"
  PHI: "medium"
  PD: "high"
metadata:
  description: "Only communicate with secure SMTP connections."
  remediation_message: ""
  dsr_id: "DSR-2"
  id: "ruby_rails_insecure_smtp"
