type: "risk"
patterns:
  - pattern: |
      Rails.logger.info($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
languages:
  - ruby
trigger: "local"
severity:
  default: "low"
  PII: "critical"
  PHI: "medium"
  PD: "high"
skip_data_types:
  - "Unique Identifier"
metadata:
  description: "Do not send sensitive data to loggers."
  remediation_message: ""
  dsr_id: "DSR-5"
