patterns:
  - pattern: |
      Rails.logger.$<METHOD>($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
      - variable: METHOD
        values:
          # - debug
          - info
          - warn
          - error
          - fatal
          - unknown
languages:
  - ruby
trigger: local
severity:
  default: low
  PII: critical
  PHI: medium
  PD: high
skip_data_types:
  - "Unique Identifier"
metadata:
  description: "Sensitive data sent to Rails loggers detected."
  remediation_message: |
    ## Description
    Leaking sensitive data to loggers is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to rails loggers.

    ## Remediations
    ❌ Avoid using sensitive data in logger messages:

    ```ruby
    Rails.logger.info('User is: #{user.email}')
    ```

    ✅ If you need to identify a user, ensure to use their unique identifier instead of their personal identifiable information:

    ```ruby
    Rails.logger.info('User is: #{user.uuid}')
    ```
    <!--
    ## Resources
    Coming soon.
    -->
  cwe_id:
    - 209
    - 532
  id: ruby_rails_logger
