type: "risk"
languages:
  - ruby
patterns:
  - pattern: |
      class $ANYTHING < ApplicationRecord
        validates :password, length: { minimum: $LENGTH }
      end
    filters:
      - variable: LENGTH
        minimum: 8
        match_violation: true
  - pattern: |
      class $ANYTHING < ApplicationRecord
        devise password_length: $MIN_LENGTH..$MAX_LENGTH
      end
    filters:
      - variable: MAX_LENGTH
        minimum: 35
        match_violation: true
      - variable: MIN_LENGTH
        minimum: 8
        match_violation: true
  - pattern: |
      Devise.setup do |config|
        config.password_length = $MIN_LENGTH..$MAX_LENGTH
      end
    filters:
      - variable: MIN_LENGTH
        minimum: 8
        match_violation: true
  - pattern: |
      Devise.setup do |config|
        config.password_length = $LENGTH
      end
    filters:
      - variable: LENGTH
        minimum: 8
        match_violation: true
detect_presence: true
trigger: "global"
severity:
  default: "high"
metadata:
  failure_message: "failure message DSW-007"
  description: "description DSW-007"
  remediation_message: "remediation message DSW-007"
  dsw_id: "DSW-007"
