type: "risk"
patterns:
  - pattern: |
      session[] = $<DATA_TYPE>
    filters:
      - variable: DATA_TYPE
        detection: datatype
languages:
  - ruby
trigger: "local"
severity:
  default: "low"
  PII: "critical"
  PHI: "medium"
  PD: "high"
metadata:
  failure_message: "failure message DSW-004"
  description: "description DSW-004"
  remediation_message: "remediation message DSW-004"
  dsw_id: "DSW-004"
