patterns:
  - pattern: |
      session[$<USER_INPUT>]
    filters:
      - variable: USER_INPUT
        detection: ruby_rails_session_key_using_user_input_user_input
auxiliary:
  - id: ruby_rails_session_key_using_user_input_user_input
    patterns:
      - params
      - request
      - cookies
languages:
  - ruby
trigger: presence
severity: high
metadata:
  description: "User input detected in a session key."
  remediation_message: |
    ## Description
    Using user-defined data in a session key is bad practice and can allow attackers to perform unsafe actions.

    <!--
    ## Remediations
    Coming soon.
    ## Resources
    Coming soon.
    -->
  cwe_id:
    - 276
  id: ruby_rails_session_key_using_user_input
