type: "risk"
patterns:
  - pattern: |
      session[] = $<DATA_TYPE>
    filters:
      - variable: DATA_TYPE
        detection: datatype
languages:
  - ruby
trigger: "local"
severity:
  default: "low"
  PII: "critical"
  PHI: "medium"
  PD: "high"
metadata:
  description: "Do not store sensitive data in session cookies."
  remediation_message: ""
  dsr_id: "DSR-3"
  id: "ruby_rails_session"
