includes:
  - from_file:
      path: ./.goreleaser/common.yaml

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  draft: false
  mode: append

brews:
  - # Name template of the recipe
    name: bearer
    folder: Formula
    install: bin.install "bearer"
    tap:
      owner: Bearer
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    commit_author:
      name: bearer
      email: bearer@users.noreply.github.com

    commit_msg_template: "chore: Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    homepage: "https://bearer.com"

    license: "Elastic License 2.0"

    description: "A data-first security scanner that finds risks and vulnerabilities in your code so you can protect sensitive data (PHI, PD, PII)."

dockers:
  - image_templates:
      - "docker.io/bearer/bearer:{{ .Tag }}-amd64"
      - "docker.io/bearer/bearer:{{ .Version }}-amd64"
      - "docker.io/bearer/bearer:latest-amd64"
      - "ghcr.io/bearer/bearer:{{ .Tag }}-amd64"
      - "ghcr.io/bearer/bearer:{{ .Version }}-amd64"
      - "ghcr.io/bearer/bearer:latest-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    ids:
      - linux
    build_flag_templates:
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=A data-first security scanner that finds risks and vulnerabilities in your code so you can protect sensitive data (PHI, PD, PII)."
      - "--label=org.opencontainers.image.vendor=Bearer"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/bearer/bearer"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.url=https://bearer.com"
      - "--label=org.opencontainers.image.documentation=https://docs.bearer.com"
      - "--platform=linux/amd64"

announce:
  discord:
    enabled: true
    message_template: |
      Bearer {{ .Tag }} is out now! Check it out: https://github.com/bearer/bearer/releases/tag/{{ .Tag }}

      {{ .ReleaseNotes }}

nfpms:
  -
    formats:
      - deb
      - rpm
      - archlinux
    vendor: Bearer
    homepage: "https://bearer.com"
    maintainer: "Bearer <dev@bearer.sh>"
    description: "A data-first security scanner that finds risks and vulnerabilities in your code so you can protect sensitive data (PHI, PD, PII)."
    license: "Elastic License 2.0"
    file_name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    dependencies:
      - git

furies:
  -
    account: bearer
    secret_name: FURY_TOKEN
