patterns:
  - pattern: |
      $<CLIENT>.index($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
      - variable: CLIENT
        values:
          - client
          - elasticsearch
          - es
languages:
  - javascript
trigger: local
metadata:
  description: "Sensitive data sent to ElasticSearch detected."
  remediation_message: |
    ## Description

    Leaking sensitive data to database is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to elasticsearch.

    ## Remediations

    <!--
    ## Resources
    Coming soon.
    -->
  cwe_id:
    - 201
  id: "javascript_elasticsearch"
