patterns:
  - pattern: |
      gtag($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
languages:
  - javascript
skip_data_types:
  - "Unique Identifier"
trigger: local
metadata:
  description: "Sensitive data sent to Google Analytic detected."
  remediation_message: |
    ## Description

    Leaking sensitive data to third-party analytics tools is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to Google Analytics.

    ## Remediations

    When sending data to analytics libraries, ensure all sensitive data is removed.

    If you really need to identify users, use unique identifiers from the database.

    ```javascript
      gtag("event", "screen_view", {
        user: {
          subscribed: true,
        },
      });
    ```

    ## Resources
    - [OWASP logging cheat sheet](https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html)

  cwe_id:
    - 201
  id: "javascript_google_analytics"
