patterns:
  - pattern: |
      $<HONEYBADGER>.$<METHOD>($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
      - variable: HONEYBADGER
        values:
          - Honeybadger
          - honeybadger
      - variable: METHOD
        values:
          - setContext
          - notify
          - notifyAsync
languages:
  - javascript
trigger: local
severity:
  default: low
  PII: critical
  PHI: medium
  PD: high
metadata:
  description: "Do not send sensitive data to Honeybadger."
  remediation_message: |
    ## Description

    Leaking sensitive data to third-party error logging tools is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to Honeybadger.

    ## Remediations

    When sending data to logging libraries, ensure all sensitive data is removed.

    <!--
    ## Resources
    Coming soon.
    -->
  dsr_id: DSR-1
  cwe_id:
    - 201
  id: "javascript_honeybadger"
