patterns:
  - pattern: |
      $<CLIENT>.$<METHOD>($<_>, $<DATA_TYPE>)
    filters:
      - variable: CLIENT
        values:
          - newrelic
          - newRelic
          - client
      - variable: DATA_TYPE
        detection: datatype
      - variable: METHOD
        values:
          - noticeError
          - setCustomAttribute
  - pattern: |
      $<CLIENT>.$<METHOD>($<DATA_TYPE>, $<_>)
    filters:
      - variable: CLIENT
        values:
          - newrelic
          - newRelic
          - client
      - variable: DATA_TYPE
        detection: datatype
      - variable: METHOD
        values:
          - setPageViewName
  - pattern: |
      $<INTERACTION>.setAttribute($<_>, $<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
      - variable: INTERACTION
        detection: javascript_new_relic_interaction
languages:
  - javascript
auxiliary:
  - id: javascript_new_relic_interaction
    patterns:
      - pattern: |
          $<CLIENT>.interaction()
        filters:
          - variable: CLIENT
            values:
              - newrelic
              - newRelic
              - client
trigger: local
severity:
  default: low
  PII: critical
  PHI: medium
  PD: high
metadata:
  description: "Do not send sensitive data to New Relic."
  remediation_message: |
    ## Description
    Leaking sensitive data to third-party loggers is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to New Relic.

    ## Remediations

    When logging errors or events, ensure all sensitive data is removed.

    ## Resources
    - [New Relic Docs](https://docs.newrelic.com/)
    - [Log obfuscation](https://docs.newrelic.com/docs/logs/ui-data/obfuscation-ui/)
  dsr_id: DSR-1
  cwe_id:
    - 201
  id: "javascript_third_parties_new_relic"
