patterns:
  - pattern: |
      $<SPAN>.$<METHOD>($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: SPAN
        detection: javascript_third_parties_open_telemetry_span
      - variable: DATA_TYPE
        detection: datatype
      - variable: METHOD
        values:
          - addEvent
          - recordException
          - setAttribute
          - setStatus
languages:
  - javascript
auxiliary:
  - id: javascript_third_parties_open_telemetry_span
    patterns:
      - opentelemetry.trace.getSpan()
      - span
trigger: local
severity:
  default: low
  PII: critical
  PHI: medium
  PD: high
skip_data_types:
  - "Unique Identifier"
metadata:
  description: "Do not send sensitive data to Open Telemetry."
  remediation_message: |
    ## Description
    Leaking sensitive data to third-party loggers is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to Open Telemetry.

    ## Remediations

    When logging errors or events, ensure all sensitive data is removed.

    ## Resources
    - [Open Telemetry Docs](https://opentelemetry.io/docs/)
  dsr_id: DSR-1
  id: javascript_third_parties_open_telemetry
