patterns:
  - pattern: |
      $<PASSPORT>($<STRATEGY>)
    filters:
      - variable: PASSPORT
        detection: javascript_third_parties_passport_hardcoded_secret_passport_usage
      - variable: STRATEGY
        detection: javascript_third_parties_passport_strategy
auxiliary:
  - id: javascript_third_parties_passport_strategy
    patterns:
      - pattern: |
          new $<METHOD>($<CONFIG>)
        filters:
          - variable: METHOD
            values:
              - Strategy
              - LocalStrategy
              - HTTPBearerStrategy
              - BearerStrategy
              - GoogleStrategy
              - GoogleOauthStrategy
              - TwitterStrategy
              - JwtStrategy
              - FacebookStrategy
              - CognitoStrategy
          - variable: CONFIG
            detection: javascript_third_parties_passport_hardcoded_secret_secret_usage
  - id: javascript_third_parties_passport_hardcoded_secret_secret_usage
    patterns:
      - pattern: |
          { clientSecret: $<STRING_LITERAL> }
        filters:
          - variable: STRING_LITERAL
            detection: string_literal
            contains: false
      - pattern: |
          { secretOrKey: $<STRING_LITERAL> }
        filters:
          - variable: STRING_LITERAL
            detection: string_literal
            contains: false
      - pattern: |
          { consumerSecret: $<STRING_LITERAL> }
        filters:
          - variable: STRING_LITERAL
            detection: string_literal
            contains: false
  - id: javascript_third_parties_passport_hardcoded_secret_passport_usage
    patterns:
      - passport.use
languages:
  - javascript
trigger: presence
severity: high
metadata:
  description: "Hardcoded passport secret detected"
  remediation_message: |
    ## Description

    Code is not a safe place to store secrets, use environment variables instead.

    ##  Remediations

    Use environment variables instead

    ```javascript
      const strategy = new GoogleStrategy({ clientSecret: process.ENV.GOOGLE_SECRET });
      passport.use(strategy);
    ```

    ## Resources
    - [OWASP hardcoded passwords](https://owasp.org/www-community/vulnerabilities/Use_of_hard-coded_password)

  dsr_id: "DSR-5"
  cwe_id:
    - 798
  id: "javascript_third_parties_passport_hardcoded_secret"
