patterns:
  - pattern: |
      $<PASSPORT>($<STRATEGY>)
    filters:
      - variable: PASSPORT
        detection: javascript_third_parties_passport_hardcoded_secret_passport_usage
      - variable: STRATEGY
        detection: javascript_third_parties_passport_strategy
auxiliary:
  - id: javascript_third_parties_passport_strategy
    patterns:
      - pattern: |
          new $<METHOD>($<CONFIG>)
        filters:
          - variable: METHOD
            values:
              - Strategy
              - LocalStrategy
              - HTTPBearerStrategy
              - BearerStrategy
              - GoogleStrategy
              - GoogleOauthStrategy
              - TwitterStrategy
              - JwtStrategy
              - FacebookStrategy
              - CognitoStrategy
          - variable: CONFIG
            detection: javascript_third_parties_passport_hardcoded_secret_secret_usage
  - id: javascript_third_parties_passport_hardcoded_secret_secret_usage
    patterns:
      - pattern: |
          { clientSecret: $<_:string> }
      - pattern: |
          { secretOrKey: $<_:string> }
      - pattern: |
          { consumerSecret: $<_:string> }
  - id: javascript_third_parties_passport_hardcoded_secret_passport_usage
    patterns:
      - passport.use
languages:
  - javascript
trigger: presence
severity:
  default: critical
metadata:
  description: "Hardcoded passport secret detected"
  remediation_message: |
    ## Description

    Code is not a safe place to store secrets, use environment variables instead.

    <!--
    ## Resources
    Coming soon.
    -->
  dsr_id: "DSR-5"
  cwe_id:
    - 798
  id: "javascript_third_parties_passport_hardcoded_secret"
