patterns:
  - pattern: |
      Sentry.$<METHOD>($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
      - variable: METHOD
        values:
          - addBreadcrumb
          - captureMessage
          - captureEvent
          - captureException
  - pattern: |
      $<SCOPE>.$<METHOD>($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: SCOPE
        detection: javascript_third_parties_sentry_scope
      - variable: DATA_TYPE
        detection: datatype
      - variable: METHOD
        values:
          - setUser
          - setTag
          - setExtra
auxiliary:
  - id: javascript_third_parties_sentry_scope
    patterns:
      - |
        Sentry.configureScope(($<!>$<_>) => {})
languages:
  - javascript
trigger: local
severity:
  default: low
  PII: critical
  PHI: medium
  PD: high
skip_data_types:
  - "Unique Identifier"
metadata:
  description: "Sensitive data sent to Sentry detected."
  remediation_message: |
    ## Description
    Leaking sensitive data to third-party loggers is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to Sentry.

    ## Remediations

    When logging errors or events, ensure all sensitive data is removed.

    ## Resources
    - [Sentry Docs](https://docs.sentry.io/)
  dsr_id: DSR-1
  cwe_id:
    - 201
  associated_recipe: Sentry
  id: javascript_third_parties_sentry
