patterns:
  - pattern: |
      document.$<METHOD>($<...>$<DATA>$<...>)
    filters:
      - variable: METHOD
        values:
          - write
          - writeLn
      - not:
          variable: DATA
          detection: javascript_dangerous_insert_html_sanitzed_input
  - pattern: |
      $<_>.$<PROPERTY> = $<DATA>
    filters:
      - variable: PROPERTY
        values:
          - outerHTML
          - innerHTML
      - not:
          variable: DATA
          detection: javascript_dangerous_insert_html_sanitzed_input
  - pattern: |
      $<SOURCE>.$<METHOD>($<...>$<DATA>$<...>)
    filters:
      - not:
          variable: SOURCE
          values:
            - React
      - variable: METHOD
        values:
          - setHTML
          - insertAdjacentHTML
          - createElement
          - replaceWith
          - replaceChildren
      - not:
          variable: DATA
          detection: javascript_dangerous_insert_html_sanitzed_input
auxiliary:
  - id: javascript_dangerous_insert_html_sanitzed_input
    patterns:
      - pattern: |
          $<STRING_LITERAL>
        filters:
          - variable: STRING_LITERAL
            detection: string_literal
            contains: false
      - pattern: |
          $<EMPTY_STRING>
        filters:
          - variable: EMPTY_STRING
            regex: (""|''|``)
      - $<_>.sanitize()
      - $<_>.sanitizeHTML()
  - id: javascript_dangerous_insert_html_unsanitzed_input
    patterns:
      - |
        `$<...>${$<...>$<_>$<...>}$<...>`
languages:
  - javascript
trigger: presence
severity: high
metadata:
  description: "Dangerous dynamic HTML insert detected."
  remediation_message: |
    ## Description

    TODO

    ## Remediations

    TODO

    <!--
    ## Resources
    Coming soon.
    -->
  cwe_id:
    - 79
  id: "javascript_dangerous_insert_html"
