patterns:
  - pattern: |
      { $<KEY>: $<ANTYHING:string> }
    filters:
      - variable: KEY
        values:
          - clientSecret
          - secretOrKey
          - consumerSecret
  - pattern: |
      $<_>.$<KEY> = $<ANTYHING:string>
    filters:
      - variable: KEY
        values:
          - clientSecret
          - secretOrKey
          - consumerSecret
languages:
  - javascript
trigger: presence
severity:
  default: critical
metadata:
  description: "Hardcoded secret detected"
  remediation_message: |
    ## Description

    Code is not a safe place to store secrets, use enviorment variables instead.

    <!--
    ## Resources
    Coming soon.
    -->
  dsr_id: "DSR-5"
  cwe_id:
    - 95
  id: "javascript_hardcoded_secret"
