patterns:
  - pattern: |
      { $<KEY>: $<STRING_LITERAL> }
    filters:
      - variable: KEY
        values:
          - clientSecret
          - secretOrKey
          - consumerSecret
      - variable: STRING_LITERAL
        detection: string_literal
        contains: false
  - pattern: |
      $<_>.$<KEY> = $<STRING_LITERAL>
    filters:
      - variable: KEY
        values:
          - clientSecret
          - secretOrKey
          - consumerSecret
      - variable: STRING_LITERAL
        detection: string_literal
        contains: false
languages:
  - javascript
trigger: presence
severity: high
metadata:
  description: "Hardcoded secret detected"
  remediation_message: |
    ## Description

    Code is not a safe place to store secrets, use environment variables instead.

    ## Remediations
    ```javascript
      passport.use(new OAuth2Strategy({
          authorizationURL: 'https://www.example.com/oauth2/authorize',
          tokenURL: 'https://www.example.com/oauth2/token',
          clientID:  process.env.CLIENT_ID,
          clientSecret: process.env.CLIENT_SECRET,
          callbackURL: "http://localhost:3000/auth/example/callback"
        },
        function(accessToken, refreshToken, profile, cb) {
          User.findOrCreate({ exampleId: profile.id }, function (err, user) {
            return cb(err, user);
          });
        }
      ));
    ```

    ## Resources
    - [OWASP hardcoded passwords](https://owasp.org/www-community/vulnerabilities/Use_of_hard-coded_password)

  dsr_id: "DSR-5"
  cwe_id:
    - 798
  id: "javascript_hardcoded_secret"
