patterns:
  - pattern: |
      { $<KEY>: $<STRING_LITERAL> }
    filters:
      - variable: KEY
        values:
          - clientSecret
          - secretOrKey
          - consumerSecret
      - variable: STRING_LITERAL
        detection: string_literal
        contains: false
  - pattern: |
      $<_>.$<KEY> = $<STRING_LITERAL>
    filters:
      - variable: KEY
        values:
          - clientSecret
          - secretOrKey
          - consumerSecret
      - variable: STRING_LITERAL
        detection: string_literal
        contains: false
languages:
  - javascript
trigger: presence
severity:
  default: critical
metadata:
  description: "Hardcoded secret detected"
  remediation_message: |
    ## Description

    Code is not a safe place to store secrets, use environment variables instead.

    <!--
    ## Resources
    Coming soon.
    -->
  dsr_id: "DSR-5"
  cwe_id:
    - 798
  id: "javascript_hardcoded_secret"
