patterns:
  - pattern: |
      $<LIBRARY>.$<METHOD>($<INSECURE_URL>$<...>)
    filters:
      - variable: INSECURE_URL
        detection: insecure_url
      - variable: LIBRARY
        values:
          - axios
          - http
      - variable: METHOD
        values:
          - get
          - post
          - patch
          - delete
  - pattern: |
      axios($<INSECURE_CONFIG>)
    filters:
      - variable: INSECURE_CONFIG
        detection: javascript_http_insecure_axios_object
  - pattern: |
      fetch($<INSECURE_URL>$<...>)
    filters:
      - variable: INSECURE_URL
        detection: insecure_url
  - pattern: |
      $<REQUEST>.open($<_>, $<INSECURE_URL>$<...>);
    filters:
      - variable: INSECURE_URL
        detection: insecure_url
      - variable: REQUEST
        values:
          - req
          - request
          - xhttp
auxiliary:
  - id: javascript_http_insecure_axios_object
    patterns:
      - pattern: |
          { url: $<INSECURE_URL> }
        filters:
          - variable: INSECURE_URL
            detection: insecure_url
languages:
  - javascript
trigger: presence
severity:
  default: low
metadata:
  description: "Connection with an unsecure HTTP communication detected."
  remediation_message: |
    ## Description

    Applications processing sensitive data should only connect using HTTPS connections. This rule checks that all HTTP connections use HTTPS.

    ❌ Avoid using unsecured outgoing HTTP communication, especially in the context of API calls:

    ```javascript
    const response = axios.get('http://insecure-api.com')
    ```

    ✅ Ensure to always connect though HTTPS:

    ```javascript
    const response = axios.get('https://secure-api.com')
    ```

    <!--
    ## Resources
    Coming soon.
    -->
  cwe_id:
    - 319
  id: "javascript_http_insecure"
