type: risk
patterns:
  - pattern: |
      jwt.sign($<_>, $<_>, {
        algorithm: "none"
      })
languages:
  - javascript
trigger: presence
metadata:
  description: "Weak jwt encryption deceted"
  remediation_message: |
    ## Description

    Use any default encryption algorithm jwt library provides

    ## Remediations

    Use the HS256 algorithm for JWT encryption

    ```
      jwt.sign({ "foo": "bar"}, process.env.JWT_SECRET, {
        algorithm: "HS256"
      })
    ```

    ## Resources
    - [OWASP weak encryption](https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/04-Testing_for_Weak_Encryption)

  dsr_id: "DSR-5"
  cwe_id:
    - 327
  id: "javascript_jwt_weak_encryption"
