type: risk
patterns:
  - pattern: |
      jwt.sign($<_>, $<SECRET:string>)
languages:
  - javascript
trigger: presence
severity:
  default: medium
skip_data_types:
  - "Unique Identifier"
metadata:
  description: "Hardocded jwt secret deteted"
  remediation_message: |
    ## Description

    Code is not a secure place to store secrets, use env variable.


    <!--
    ## Resources
    Coming soon.
    -->
  dsr_id: "DSR-5"
  cwe_id:
    - 798
  id: "javascript_jwt_hardcoded_secret"
