type: risk
patterns:
  - pattern: |
      jwt.sign($<_>, $<STRING_LITERAL>)
    filters:
      - variable: STRING_LITERAL
        detection: string_literal
        contains: false
languages:
  - javascript
trigger: presence
severity:
  default: medium
metadata:
  description: "Hardcoded jwt secret deteted"
  remediation_message: |
    ## Description

    Code is not a secure place to store secrets, use env variable.


    <!--
    ## Resources
    Coming soon.
    -->
  dsr_id: "DSR-5"
  cwe_id:
    - 798
  id: "javascript_jwt_hardcoded_secret"
