type: risk
patterns:
  - pattern: |
      jwt.sign($<_>, $<STRING_LITERAL>)
    filters:
      - variable: STRING_LITERAL
        detection: string_literal
        contains: false
  - pattern: |
      $<JOSE_SIGN_JWT>.sign($<STRING_LITERAL>)
    filters:
      - variable: JOSE_SIGN_JWT
        pattern:
          - |
            jose.SignJWT().$<...>
      - variable: STRING_LITERAL
        detection: string_literal
        contains: false
languages:
  - javascript
trigger: presence
severity: high
metadata:
  description: "Hardcoded jwt secret deteted"
  remediation_message: |
    ## Description

    Code is not a secure place to store secrets, use environment variables instead.

    ## Remediations

    Use environment variables

    ```javascript
      var jwt = require("jsonwebtoken");

      var token = jwt.sign({ foo: "bar" }, process.env.JWT_SECRET);
    ```

    ## Resources
    - [OWASP hardcoded passwords](https://owasp.org/www-community/vulnerabilities/Use_of_hard-coded_password)

  dsr_id: "DSR-5"
  cwe_id:
    - 798
  id: "javascript_jwt_hardcoded_secret"
