type: "risk"
patterns:
  - pattern: |
      logger.$<METHOD>($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
      - variable: METHOD
        values:
          - warn
          - info
          - error
          - fatal
          - log
  - pattern: |
      log.$<METHOD>($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
      - variable: METHOD
        values:
          - warn
          - info
          - error
          - fatal
          - log
  - pattern: |
      console.$<METHOD>($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
      - variable: METHOD
        values:
          - error
          - log
          - table
          - info
          - warn
  # fixme: bring elipsis support in javascript
  # - pattern: |
  #     logger.child($<DATA_TYPE>)$<...>
  #   filters:
  #     - variable: DATA_TYPE
  #       detection: datatype
  - pattern: |
      $<VAR>.$<METHOD>($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
      - variable: VAR
        detection: child_logger
      - variable: METHOD
        values:
          - warn
          - info
          - error
          - fatal
          - log
auxiliary:
  - id: child_logger
    type: verifier
    patterns:
      - |
        logger.child()
    languages:
      - javascript
languages:
  - javascript
trigger: "local"
severity:
  default: "low"
  PII: "critical"
  PHI: "medium"
  PD: "high"
skip_data_types:
  - "Unique Identifier"
metadata:
  description: "Do not send sensitive data to loggers."
  remediation_message: |
    ## Description

    Leaking sensitive data to loggers is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to loggers.

    ## Remediations

    ❌ Avoid using sensitive data in logger messages:

    ```javascript
    logger.info(`User is: ${user.email}`)
    ```

    ✅ If you need to identify a user, ensure to use their unique identifier instead of their personal identifiable information:

    ```javascript
    logger.info(`User is: ${user.uuid}`)
    ```
    <!--
    ## Resources
    Coming soon.
    -->
  dsr_id: "DSR-5"
  id: "javascript_lang_logger"
