patterns:
  - pattern: |
      $<LOG>.$<METHOD>($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
      - variable: METHOD
        values:
          - warn
          - info
          - error
          - fatal
          - log
      - variable: LOG
        values:
          - log
          - logger
  - pattern: |
      console.$<METHOD>($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
      - variable: METHOD
        values:
          - warn
          - info
          - error
          - log
          - table
  - pattern: |
      $<LOG>.child($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
      - variable: LOG
        values:
          - log
          - logger
  - pattern: |
      $<VAR>.$<METHOD>($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
      - variable: VAR
        detection: child_logger
      - variable: METHOD
        values:
          - warn
          - info
          - error
          - fatal
          - log
auxiliary:
  - id: child_logger
    patterns:
      - pattern: |
          $<LOG>.child()
        filters:
          - variable: LOG
            values:
              - log
              - logger
languages:
  - javascript
trigger: local
severity:
  default: low
  PII: critical
  PHI: medium
  PD: high
skip_data_types:
  - "Unique Identifier"
metadata:
  description: "Do not send sensitive data to loggers."
  remediation_message: |
    ## Description

    Leaking sensitive data to loggers is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to loggers.

    ## Remediations

    ❌ Avoid using sensitive data in logger messages:

    ```javascript
    logger.info(`User is: ${user.email}`)
    ```

    ✅ If you need to identify a user, use their unique identifier instead of their personal identifiable information:

    ```javascript
    logger.info(`User is: ${user.uuid}`)
    ```
    <!--
    ## Resources
    Coming soon.
    -->
  dsr_id: "DSR-5"
  cwe_id:
    - 1295
    - 532
  id: "javascript_lang_logger"
