patterns:
  - pattern: |
      localStorage.setItem($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
languages:
  - javascript
trigger: local
skip_data_types:
  - "Unique Identifier"
metadata:
  description: "Sensitive data stored in HTML local storage detected."
  remediation_message: |
    ## Description

    Sensitive data should not be stored in a `localStorage` session. This policy looks for any sensitive data stored within the localstorage.

    ## Remediations

    It's best to avoid storing sensitive data in `localStorage` whenever possible. To keep session data safe, use a server-based session storage solution instead.

    ❌ If you do need do store data in `localStorage`, avoid including sensitive data:

    ```javascript
    localStorage.setItem('user', email)
    ```

     ✅ Instead, use a unique identifier:

    ```javascript
    localStorage.setItem('user', user.uuid)
    ```

    ## Resources
      - [OWASP sensitive data exposure](https://owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure)
  cwe_id:
    - 312
  id: "javascript_session"
