patterns:
  - pattern: |
      localStorage.setItem($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
languages:
  - javascript
trigger: local
severity:
  default: low
  PII: critical
  PHI: medium
  PD: high
skip_data_types:
  - "Unique Identifier"
metadata:
  description: "Do not set sensitive data to session."
  remediation_message: |
    ## Description

    Sensitive data should not be stored in a `localStorage` session. This policy looks for any sensitive data stored within the localstorage.

    ## Remediations

    It's best to avoid storing sensitive data in `localStorage` whenever possible. To keep session data safe, use a server-based session storage solution instead.

    ❌ If you do need do store data in `localStorage`, avoid including sensitive data:

    ```javascript
    localStorage.setItem('user', email)
    ```

     ✅ Instead, use a unique identifier:

    ```javascript
    localStorage.setItem('user', user.uuid)
    ```

    <!--
    ## Resources
    Coming soon.
    -->
  dsr_id: "DSR-5"
  id: "javascript_session"
