export const _HANDLER = 'MyHandler'
export const BEARER_XRAY_LOG_GROUP = 'MyLOgGroup'
export const AWS_LAMBDA_LOG_STREAM_NAME = 'MyLogStreamName'
export const STAGE = 'test'
export const _X_AMZN_TRACE_ID = 'Root=is-uuid;Parent=my-uuid'
