/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  Authentications,
} from './components/setup/types';


export namespace Components {

  interface BearerSaveSetup {
    /**
    * Your Bearer clientId
    */
    'clientId': string;
    /**
    * Integration identifier
    */
    'integration': string;
    'noError': boolean;
    /**
    * Optionally provide your custom setupId
    */
    'setupId'?: string;
    /**
    * Authentication Type of the integration
    */
    'type': Authentications | 'unknown';
  }
  interface BearerSaveSetupAttributes extends StencilHTMLAttributes {
    /**
    * Your Bearer clientId
    */
    'clientId'?: string;
    /**
    * Integration identifier
    */
    'integration'?: string;
    'noError'?: boolean;
    'onSaved'?: (event: CustomEvent<{ setupId: string }>) => void;
    /**
    * Optionally provide your custom setupId
    */
    'setupId'?: string;
    /**
    * Authentication Type of the integration
    */
    'type'?: Authentications | 'unknown';
  }
}

declare global {
  interface StencilElementInterfaces {
    'BearerSaveSetup': Components.BearerSaveSetup;
  }

  interface StencilIntrinsicElements {
    'bearer-save-setup': Components.BearerSaveSetupAttributes;
  }


  interface HTMLBearerSaveSetupElement extends Components.BearerSaveSetup, HTMLStencilElement {}
  var HTMLBearerSaveSetupElement: {
    prototype: HTMLBearerSaveSetupElement;
    new (): HTMLBearerSaveSetupElement;
  };

  interface HTMLElementTagNameMap {
    'bearer-save-setup': HTMLBearerSaveSetupElement
  }

  interface ElementTagNameMap {
    'bearer-save-setup': HTMLBearerSaveSetupElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
