patterns:
  - pattern: |
      { __html: $<DATA> }
    filters:
      - not:
          variable: DATA
          detection: javascript_react_dangerously_set_inner_html_sanitzed_input
auxiliary:
  - id: javascript_react_dangerously_set_inner_html_sanitzed_input
    patterns:
      - pattern: |
          $<STRING_LITERAL>
        filters:
          - variable: STRING_LITERAL
            detection: string_literal
            contains: false
      - sanitize($<_>)
      - sanitizeHTML($<_>)
languages:
  - javascript
trigger: presence
severity: high
metadata:
  description: "React's dangerously set inner HTML detected."
  remediation_message: |
    ## Description
    There are XSS vulnerabilites when using React's dangerouslySetInnerHTML with unsanitized data.

    <!--
    ## Remediations
    Coming soon.
    ## Resources
    Coming soon.
    -->
  cwe_id:
    - 79
  id: "javascript_react_dangerously_set_inner_html"
