/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@bearer/stencil-core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface {{scenarioTitle}} {
    }
  }

  interface HTML{{scenarioTitle}}Element extends StencilComponents.{{scenarioTitle}}, HTMLStencilElement {}

  var HTML{{scenarioTitle}}Element: {
    prototype: HTML{{scenarioTitle}}Element;
    new (): HTML{{scenarioTitle}}Element;
  };
  interface HTMLElementTagNameMap {
    '{{scenarioTitle}}': HTML{{scenarioTitle}}Element;
  }
  interface ElementTagNameMap {
    '{{scenarioTitle}}': HTML{{scenarioTitle}}Element;
  }
  namespace JSX {
    interface IntrinsicElements {
      '{{scenarioTitle}}': JSXElements.{{scenarioTitle}}Attributes;
    }
  }
  namespace JSXElements {
    export interface {{scenarioTitle}}Attributes extends HTMLAttributes {
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
