enum Events {
  SESSION_INITIALIZED = 'BEARER_SESSION_INITIALIZED',
  COOKIE_SETUP = 'BEARER_COOKIE_SETUP',
  HAS_AUTHORIZED = 'BEARER_HAS_AUTHORIZED',
  AUTHORIZED = 'BEARER_AUTHORIZED',
  REVOKE = 'BEARER_REVOKE',
  REVOKED = 'BEARER_REVOKED'
}

export default Events
