enum Events {
  BEARER_SESSION_INITIALIZED = 'BEARER_SESSION_INITIALIZED',
  BEARER_AUTHORIZED = 'BEARER_AUTHORIZED',
  SCENARIO_AUTHORIZED = 'SCENARIO_AUTHORIZED',
  BEARER_COOKIE_SETUP = 'BEARER_COOKIE_SETUP'
}

export default Events
