blank_issues_enabled: false
contact_links:
  - name: Not sure where to start?
    url: https://docs.bearer.com/quickstart/
    about: Try our quickstart guides.
  - name: Want to discuss your findings?
    url: https://discord.gg/eaHZBJUXRF
    about: Join our Discord community!
