medium:
    - rule:
        cwe_ids:
            - "523"
            - "522"
        id: express_default_cookie_config
        description: Cookie with default config detected.
        documentation_url: https://docs.bearer.com/reference/rules/express_default_cookie_config
      line_number: 11
      filename: default_express_session_cookie_config.js
      parent_line_number: 11
      snippet: '{}'
    - rule:
        cwe_ids:
            - "523"
            - "522"
        id: express_default_cookie_config
        description: Cookie with default config detected.
        documentation_url: https://docs.bearer.com/reference/rules/express_default_cookie_config
      line_number: 17
      filename: default_express_session_cookie_config.js
      parent_line_number: 17
      snippet: |-
        {
              domain: "example.com",
              secure: true,
              httpOnly: false,
              maxAge: 24 * 60 * 60 * 1000,
              path: "/some-path",
            }
    - rule:
        cwe_ids:
            - "523"
            - "522"
        id: express_default_cookie_config
        description: Cookie with default config detected.
        documentation_url: https://docs.bearer.com/reference/rules/express_default_cookie_config
      line_number: 29
      filename: default_express_session_cookie_config.js
      parent_line_number: 29
      snippet: |-
        {
              domain: "example.com",
              secure: true,
              httpOnly: false,
              name: "my-custom-cookie-name",
            }
    - rule:
        cwe_ids:
            - "523"
            - "522"
        id: express_default_session_config
        description: Session cookie with default config detected.
        documentation_url: https://docs.bearer.com/reference/rules/express_default_session_config
      line_number: 10
      filename: default_express_session_cookie_config.js
      parent_line_number: 10
      snippet: |-
        {
            cookie: {},
          }
    - rule:
        cwe_ids:
            - "523"
            - "522"
        id: express_default_session_config
        description: Session cookie with default config detected.
        documentation_url: https://docs.bearer.com/reference/rules/express_default_session_config
      line_number: 16
      filename: default_express_session_cookie_config.js
      parent_line_number: 16
      snippet: |-
        {
            cookie: {
              domain: "example.com",
              secure: true,
              httpOnly: false,
              maxAge: 24 * 60 * 60 * 1000,
              path: "/some-path",
            },
          }

