medium:
    - rule:
        cwe_ids:
            - "523"
            - "522"
        id: express_default_cookie_config
        description: Cookie with default config detected.
        documentation_url: https://docs.bearer.com/reference/rules/express_default_cookie_config
      line_number: 11
      filename: default_express_session_cookie_config.js
      parent_line_number: 11
      snippet: '{}'
      fingerprint: e114698a3e3b46f2392d491f2869fe33_0
    - rule:
        cwe_ids:
            - "523"
            - "522"
        id: express_default_cookie_config
        description: Cookie with default config detected.
        documentation_url: https://docs.bearer.com/reference/rules/express_default_cookie_config
      line_number: 17
      filename: default_express_session_cookie_config.js
      parent_line_number: 17
      snippet: |-
        {
              domain: "example.com",
              secure: true,
              httpOnly: false,
              maxAge: 24 * 60 * 60 * 1000,
              path: "/some-path",
            }
      fingerprint: e114698a3e3b46f2392d491f2869fe33_1
    - rule:
        cwe_ids:
            - "523"
            - "522"
        id: express_default_cookie_config
        description: Cookie with default config detected.
        documentation_url: https://docs.bearer.com/reference/rules/express_default_cookie_config
      line_number: 29
      filename: default_express_session_cookie_config.js
      parent_line_number: 29
      snippet: |-
        {
              domain: "example.com",
              secure: true,
              httpOnly: false,
              name: "my-custom-cookie-name",
            }
      fingerprint: e114698a3e3b46f2392d491f2869fe33_2
    - rule:
        cwe_ids:
            - "523"
            - "522"
        id: express_default_session_config
        description: Session cookie with default config detected.
        documentation_url: https://docs.bearer.com/reference/rules/express_default_session_config
      line_number: 10
      filename: default_express_session_cookie_config.js
      parent_line_number: 10
      snippet: |-
        {
            cookie: {},
          }
      fingerprint: 13a07ed013ea7e6baa3a2a6dfe4a3d1c_0
    - rule:
        cwe_ids:
            - "523"
            - "522"
        id: express_default_session_config
        description: Session cookie with default config detected.
        documentation_url: https://docs.bearer.com/reference/rules/express_default_session_config
      line_number: 16
      filename: default_express_session_cookie_config.js
      parent_line_number: 16
      snippet: |-
        {
            cookie: {
              domain: "example.com",
              secure: true,
              httpOnly: false,
              maxAge: 24 * 60 * 60 * 1000,
              path: "/some-path",
            },
          }
      fingerprint: 13a07ed013ea7e6baa3a2a6dfe4a3d1c_1

