low:
    - rule:
        cwe_ids:
            - "523"
            - "522"
        id: express_default_cookie_config
        description: Cookie with default config detected.
        documentation_url: https://docs.bearer.com/reference/rules/express_default_cookie_config
      line_number: 7
      filename: default_express_session_cookie_config.js
      parent_line_number: 7
      parent_content: |-
        {
        			domain: "example.com",
        			secure: true,
        			httpOnly: false,
        			maxAge: 24 * 60 * 60 * 1000,
        			path: "/some-path"
        		}
    - rule:
        cwe_ids:
            - "523"
            - "522"
        id: express_default_cookie_config
        description: Cookie with default config detected.
        documentation_url: https://docs.bearer.com/reference/rules/express_default_cookie_config
      line_number: 19
      filename: default_express_session_cookie_config.js
      parent_line_number: 19
      parent_content: |-
        {
        			domain: "example.com",
        			secure: true,
        			httpOnly: false,
        			name: "my-custom-cookie-name"
        		}


