name: ' config'
synopsis: Scan config files for misconfigurations
usage: ' config [flags] DIR'
options:
    - name: context
      usage: |
        Expand context of schema classification e.g., --context=health, to include data types particular to health
    - name: disable-domain-resolution
      default_value: "false"
      usage: |
        Do not attempt to resolve detected domains during classification (default false), e.g. --disable-domain-resolution=true
    - name: domain-resolution-timeout
      default_value: 3s
      usage: |
        Set timeout when attempting to resolve detected domains during classification (default 3 seconds), e.g. --domain-resolution-timeout=3s
    - name: help
      shorthand: h
      default_value: "false"
      usage: help for config
    - name: internal-domains
      default_value: '[]'
      usage: |
        Define regular expressions for better classification of private or unreachable domains e.g. --internal-domains="*.my-company.com,private.sh"
    - name: skip-path
      default_value: '[]'
      usage: |
        Specify the comma separated files and directories to skip. Supports * syntax, e.g. --skip-path users/*.go,users/admin.sql
see_also:
    - ' - '
aliases: conf
