high:
    - rule:
        cwe_ids:
            - "201"
        id: javascript_third_parties_sentry
        description: Sensitive data sent to Sentry detected.
        documentation_url: https://docs.bearer.com/reference/rules/javascript_third_parties_sentry
      line_number: 2
      filename: javascript_configure_scope_set_extra.js
      category_groups:
        - PII
        - Personal Data
      parent_line_number: 2
      snippet: scope.setExtra("email", user.email)
      fingerprint: a6fd582e471d3774ceb8dbda2fcf2175_0

