high:
    - rule:
        cwe_ids:
            - "201"
        id: javascript_third_parties_sentry
        description: Sensitive data sent to Sentry detected.
        documentation_url: https://docs.bearer.com/reference/rules/javascript_third_parties_sentry
      line_number: 2
      filename: javascript_configure_scope_set_user.js
      category_groups:
        - PII
        - Personal Data
      parent_line_number: 2
      snippet: 'scope.setUser({ email: user.email })'
      fingerprint: 00a2e892b48a57478b26a299a26bb81e_0

