
<html>
    <head>
    </head>
    <body>
        <?php
        // not supported
        $unique = "https://api3.domain.com";
        ?>
        <script>var url = "https://inline.domain.com"</script>
        var url = "https://erb-javascript-tag.domain.com"
        <script>
            var url = "https://api1.domain.com"
        </script>
        <script type="text/javascript">
            var url = "https://api2.domain.com"
        </script>
        <script type="text/json">
            {"url":"https://ignored-api.domain.com"}
        </script>
    </body> 
</html>