type: "risk"
trigger: "presence"
severity:
  default: "critical"
detailed_context: true
omit_parent_content: true
metadata:
  description: "description DSW-012"
  remediation_message: ""
  dsr_id: "DSR-4"