patterns:
  - pattern: |
      cookies[] = $<DATA_TYPE>
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      cookies.$<METHOD>[] = $<DATA_TYPE>
    filters:
      - variable: METHOD
        values:
          - permanent
          - signed
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      cookies.permanent.signed[] = $<DATA_TYPE>
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      cookies.signed.permanent[] = $<DATA_TYPE>
    filters:
      - variable: DATA_TYPE
        detection: datatype
languages:
  - ruby
trigger: local
severity:
  default: low
  PII: critical
  PHI: medium
  PD: high
metadata:
  description: "Do not store sensitive data in cookies."
  remediation_message: |
    ## Description

    Storing sensitive data in cookies can lead to a data breach. This rule looks for instances where sensitive data is stored in browser cookies.

    ## Remediations

    ❌ Avoid storing sensitive data in unencrypted cookies messages:

    ```ruby
    cookies[:user_email] = "john@doe.com"
    ```

    ✅ To ensure cookie data stays safe, use encrypted cookies:

    ```ruby
    cookies.encrypted[:user_email] = "john@doe.com"
    ```

    ## Resources

    - Cookie object documentation: [ActionDispatch::Cookies](https://edgeapi.rubyonrails.org/classes/ActionDispatch/Cookies.html)
    - [Demystifying cookie security in rails 6](https://dev.to/ayushn21/demystifying-cookie-security-in-rails-6-1j2f#:~:text=Rails%20provides%20a%20special%20kind,data%20in%20the%20session%20cookie)
  dsr_id: DSR-3
  cwe_id:
    - 315
    - 539
  id: ruby_lang_cookies
