type: "risk"
patterns:
  - pattern: |
      $<_>.$<METHOD>($<DATA_TYPE>)
    filters:
      - variable: METHOD
        values:
          - encrypt
          - encrypt!
          - decrypt
      - variable: DATA_TYPE
        detection: datatype
languages:
  - "ruby"
trigger: "local"
severity:
  default: "low"
  PII: "critical"
  PHI: "medium"
  PD: "high"
skip_data_types:
  - "Unique Identifier"
metadata:
  description: "Do not use weak encryption libraries."
  remediation_message: ""
  dsr_id: "DSR-7"
  id: "ruby_lang_encrypt"
