patterns:
  - pattern: |
      RubyVM::InstructionSequence.compile($<USER_INPUT>$<...>)
    filters:
      - variable: USER_INPUT
        detection: ruby_lang_eval_using_user_input_user_input
  - pattern: |
      $<_>.$<METHOD>($<USER_INPUT>$<...>)
    filters:
      - variable: METHOD
        values:
          - eval
          - instance_eval
          - class_eval
          - module_eval
      - variable: USER_INPUT
        detection: ruby_lang_eval_using_user_input_user_input
  - pattern: |
      $<METHOD>($<USER_INPUT>$<...>)
    filters:
      - variable: METHOD
        values:
          - eval
          - instance_eval
          - class_eval
          - module_eval
      - variable: USER_INPUT
        detection: ruby_lang_eval_using_user_input_user_input
auxiliary:
  - id: ruby_lang_eval_using_user_input_user_input
    patterns:
      - params
      - request
      - cookies
      - | # AWS lambda
        def $<_>($<!>event:, context:)
        end
languages:
  - ruby
trigger: presence
severity:
  default: low
  PII: critical
  PHI: medium
  PD: high
metadata:
  description: "Do not generate code using user input."
  remediation_message: |
    ## Description

    TODO

    ## Remediations
    TODO
    <!--
    ## Resources
    Coming soon.
    -->
  dsr_id: DSR-? # FIXME
  cwe_id:
    - 94
  id: ruby_lang_eval_using_user_input
