type: "risk"
languages:
  - ruby
patterns:
  - pattern: |
      CSV.generate { $<DATA_TYPE> }
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      CSV.generate do
        $<DATA_TYPE>
      end
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      $<LIBRARY>.open { $<DATA_TYPE> }
    filters:
      - variable: LIBRARY
        values:
          - CSV
          - File
          - IO
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      $<LIBRARY>.open do
        $<DATA_TYPE>
      end
    filters:
      - variable: LIBRARY
        values:
          - CSV
          - File
          - IO
      - variable: DATA_TYPE
        detection: datatype
trigger: "local"
severity:
  default: "low"
  PII: "critical"
  PHI: "medium"
  PD: "high"
metadata:
  description: "Do not write sensitive data to static files."
  remediation_message: |
    ## Description

    TODO

    ## Remediations

    Coming soon.

    ## Resources

    Coming soon.
  dsr_id: "DSR-4"
  id: "ruby_lang_file_generation"
