patterns:
  - pattern: |
      Net::FTP.new($<...>$<USER_INPUT>$<...>)
    filters:
      - variable: USER_INPUT
        detection: ruby_lang_ftp_using_user_input_user_input
  - pattern: |
      Net::FTP.open($<...>$<USER_INPUT>$<...>)$<...>
    filters:
      - variable: USER_INPUT
        detection: ruby_lang_ftp_using_user_input_user_input
  - pattern: |
      $<FTP>.$<_>($<...>$<USER_INPUT>$<...>)$<...>
    filters:
      - variable: FTP
        detection: ruby_lang_ftp_using_user_input_ftp
      - variable: USER_INPUT
        detection: ruby_lang_ftp_using_user_input_user_input
auxiliary:
  - id: ruby_lang_ftp_using_user_input_user_input
    patterns:
      - params
      - request
      - cookies
      - | # AWS lambda
        def $<_>($<!>event:, context:)
        end
  - id: ruby_lang_ftp_using_user_input_ftp
    patterns:
      - Net::FTP.new()
      - Net::FTP.open()
      - Net::FTP.open() { |$<!>$<_:identifier>| }
languages:
  - ruby
trigger: presence
severity:
  default: low
  PII: critical
  PHI: medium
  PD: high
metadata:
  description: "Do not use user input to form file paths."
  remediation_message: |
    ## Description

    TODO

    ## Remediations
    TODO
    <!--
    ## Resources
    Coming soon.
    -->
  dsr_id: DSR-? # FIXME
  cwe_id:
    - 22
  id: ruby_lang_ftp_using_user_input
