patterns:
  - pattern: |
      $<NAME> = $<STRING_LITERAL>
    filters:
      - variable: NAME
        regex: (?i)password|api_?key|secret
      - variable: STRING_LITERAL
        detection: string_literal
        contains: false
  - pattern: |
      $<_>($<!>$<NAME>: $<STRING_LITERAL>)
    filters:
      - variable: NAME
        regex: (?i)password|api_?key|secret
      - variable: STRING_LITERAL
        detection: string_literal
        contains: false
  - pattern: |
      $<_>($<!>$<NAME> => $<STRING_LITERAL>)
    filters:
      - variable: NAME
        regex: (?i)['"](password|api_?key|secret)['"]
      - variable: STRING_LITERAL
        detection: string_literal
        contains: false
  - pattern: |
      { $<!>$<NAME>: $<STRING_LITERAL> }
    filters:
      - variable: NAME
        regex: (?i)password|api_?key|secret
      - variable: STRING_LITERAL
        detection: string_literal
        contains: false
  - pattern: |
      { $<!>$<NAME> => $<STRING_LITERAL> }
    filters:
      - variable: NAME
        regex: (?i)['"](password|api_?key|secret)['"]
      - variable: STRING_LITERAL
        detection: string_literal
        contains: false
languages:
  - ruby
trigger: presence
severity: high
metadata:
  description: "Hard-coded secret detected."
  remediation_message: |
    ## Description

    Applications should store secret values securely and not as literal values
    in the source code.

    ## Remediations

    ✅ Retrieve secrets from a secure location at runtime

    <!--
    ## Resources
    Coming soon.
    -->
  cwe_id:
    - 798
  id: ruby_lang_hardcoded_secret
