type: "risk"
languages:
  - ruby
patterns:
  - pattern: |
      URI($<INSECURE_URL>)
    filters:
      - variable: INSECURE_URL
        detection: insecure_url
  - pattern: |
      $<CLIENT>.get($<INSECURE_URL>)
    filters:
      - variable: CLIENT
        values:
          - Curl
          - Excon
          - Faraday
          - HTTP
          - HTTParty
          - HTTPX
          - RestClient
          - Typhoeus
    filters:
      - variable: INSECURE_URL
        detection: insecure_url
trigger: "local"
severity:
  default: "low"
  PII: "critical"
  PHI: "medium"
  PD: "high"
omit_parent_content: true
metadata:
  failure_message: "failure message DSW-010"
  description: "description DSW-010"
  remediation_message: "remediation message DSW-010"
  dsw_id: "DSW-010"
