type: "risk"
languages:
  - ruby
patterns:
  - pattern: |
      Net::HTTP.post_form($<INSECURE_URL>)
    filters:
      - variable: INSECURE_URL
        detection: insecure_url
  - pattern: |
      URI($<INSECURE_URL>)
    filters:
      - variable: INSECURE_URL
        detection: insecure_url
  - pattern: |
      $<CLIENT>.get($<INSECURE_URL>)
    filters:
      - variable: CLIENT
        values:
          - Curl
          - Excon
          - Faraday
          - HTTP
          - HTTParty
          - HTTPX
          - RestClient
          - Typhoeus
      - variable: INSECURE_URL
        detection: insecure_url
  - pattern: |
      $<CLIENT>.post($<INSECURE_URL>)
    filters:
      - variable: CLIENT
        values:
          - Curl
          - Excon
          - Faraday
          - HTTP
          - HTTParty
          - HTTPX
          - RestClient
          - Typhoeus
      - variable: INSECURE_URL
        detection: insecure_url
trigger: "presence"
severity:
  default: "low"
metadata:
  description: "Do not perform unsecure HTTP calls."
  remediation_message: ""
  dsr_id: "DSR-2"
  id: "ruby_lang_http_insecure"
