patterns:
  - |
    Net::FTP.new()
  - pattern: |
      Net::FTP.open() do
        $<DATA_TYPE>
      end
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - |
    Net::FTP.open()$<...>
languages:
  - ruby
trigger: presence
severity:
  default: low # FIXME: warning
  PHI: medium
  PII: critical
  PD: high
metadata:
  description: "Only communicate using SFTP connections."
  remediation_message: |
    ## Description

    Communication with FTP servers should be done securely over SFTP in applications that process sensitive data. This rule checks if all FTP connections are made using SFTP.

    ## Remediations

    ✅ To ensure secure FTP connections are made, [use the `Net::SFTP` library](https://github.com/net-ssh/net-sftp) instead of `Net::FTP`:

    ```ruby
    require 'net/sftp'
    Net::SFTP.start('host', 'username', password: ENV['password') do |sftp|
    	...
    end
    ```

    ## Resources
    - [net-sftp](https://github.com/net-ssh/net-sftp)
  dsr_id: DSR-2
  id: ruby_lang_insecure_ftp
