type: "risk"
patterns:
  - pattern: |
      logger.info($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
languages:
  - ruby
# auxiliary:
#   - type: "risk"
#     id: "asdf"
#     patterns:
#       - |
#         logger.asdf(<$ARGUMENT>)
#     languages:
#       - ruby
#   - type: "risk"
#     id: "qwerty"
#     patterns:
#       - |
#         logger.qwerty(<$ARGUMENT>)
#     languages:
#       - ruby
trigger: "local"
severity:
  default: "low"
  PII: "critical"
  PHI: "medium"
  PD: "high"
skip_data_types:
  - "Unique Identifier"
metadata:
  failure_message: "failure message DSW-001"
  description: "description DSW-001"
  remediation_message: "remediation message DSW-001"
  dsw_id: "DSW-001"
