type: "risk"
patterns:
  - pattern: |
      logger.$<METHOD>($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
      - variable: METHOD
        values:
          # - debug
          - warn
          - info
          - error
          - fatal
          - log
languages:
  - ruby
trigger: "local"
severity:
  default: "low"
  PII: "critical"
  PHI: "medium"
  PD: "high"
skip_data_types:
  - "Unique Identifier"
metadata:
  description: "Do not send sensitive data to loggers."
  remediation_message: |
    ## Description

    Leaking sensitive data to loggers is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to loggers.

    ## Remediations

    ❌ Avoid using sensitive data in logger messages:

    ```ruby
    logger.info('User is: #{user.email}')
    ```

    ✅ If you need to identify a user, ensure to use their unique identifier instead of their personal identifiable information:

    ```ruby
    logger.info('User is: #{user.uuid}')
    ```
    <!--
    ## Resources
    Coming soon.
    -->
  dsr_id: "DSR-5"
  id: "ruby_lang_logger"
