patterns:
  - pattern: |
      Dir[$<...>$<USER_INPUT>$<...>]
    filters:
      - variable: USER_INPUT
        detection: ruby_lang_path_using_user_input_user_input
  - pattern: |
      $<MODULE>.$<_>($<...>$<USER_INPUT>$<...>)$<...>
    filters:
      - variable: MODULE
        values:
          - Dir
          - File
          - IO
          - Pathname
      - variable: USER_INPUT
        detection: ruby_lang_path_using_user_input_user_input
  - pattern: |
      Kernel.open($<USER_INPUT>$<...>)$<...>
    filters:
      - variable: USER_INPUT
        detection: ruby_lang_path_using_user_input_user_input
  - pattern: |
      open($<USER_INPUT>$<...>)$<...>
    filters:
      - variable: USER_INPUT
        detection: ruby_lang_path_using_user_input_user_input
  - pattern: |
      PStore.new($<USER_INPUT>$<...>)
    filters:
      - variable: USER_INPUT
        detection: ruby_lang_path_using_user_input_user_input
  - pattern: |
      $<PATHNAME>.$<_>($<...>$<USER_INPUT>$<...>)
    filters:
      - variable: PATHNAME
        detection: ruby_lang_path_using_user_input_pathname
      - variable: USER_INPUT
        detection: ruby_lang_path_using_user_input_user_input
  - pattern: |
      $<PATHNAME> + $<USER_INPUT>
    filters:
      - variable: PATHNAME
        detection: ruby_lang_path_using_user_input_pathname
      - variable: USER_INPUT
        detection: ruby_lang_path_using_user_input_user_input
  - pattern: |
      $<PATHNAME> / $<USER_INPUT>
    filters:
      - variable: PATHNAME
        detection: ruby_lang_path_using_user_input_pathname
      - variable: USER_INPUT
        detection: ruby_lang_path_using_user_input_user_input
  - pattern: |
      $<METHOD>($<ARGUMENT>: $<USER_INPUT>)
    filters:
      - variable: METHOD
        values:
          - render
          - render_to_string
      - variable: ARGUMENT
        values:
          - action
          - file
          - partial
          - template
      - variable: USER_INPUT
        detection: ruby_lang_path_using_user_input_user_input
  - pattern: |
      $<METHOD>({ $<ARGUMENT>: $<USER_INPUT> })
    filters:
      - variable: METHOD
        values:
          - render
          - render_to_string
      - variable: ARGUMENT
        values:
          - action
          - file
          - partial
          - template
      - variable: USER_INPUT
        detection: ruby_lang_path_using_user_input_user_input
auxiliary:
  - id: ruby_lang_path_using_user_input_user_input
    patterns:
      - params
      - request
      - cookies
      - | # AWS lambda
        def $<_>($<!>event:, context:)
        end
  - id: ruby_lang_path_using_user_input_pathname
    patterns:
      - Rails.root
      - Pathname.$<_>
      - Pathname.$<_>()
languages:
  - ruby
trigger: presence
severity:
  default: low
  PII: critical
  PHI: medium
  PD: high
metadata:
  description: "Do not use user input to form file paths."
  remediation_message: |
    ## Description

    TODO

    ## Remediations
    TODO
    <!--
    ## Resources
    Coming soon.
    -->
  cwe_id:
    - 22
  id: ruby_lang_path_using_user_input
