languages:
  - ruby
patterns:
  - pattern: |
      $<_>.$<METHOD>($<USER_INPUT>$<...>)
    filters:
      - variable: METHOD
        values:
          - const_get
          - const_set
          - remove_const
          - class_variable_get
          - class_variable_set
          - remove_class_variable
      - variable: USER_INPUT
        detection: ruby_lang_reflection_using_user_input_user_input
  - pattern: |
      $<_>.$<METHOD>($<USER_INPUT>$<...>)$<...>
    filters:
      - variable: METHOD
        values:
          - method
          - instance_method
          - public_method
          - singleton_method
          - define_method
          - define_singleton_method
          - instance_variable_get
          - instance_variable_set
          - remove_instance_variable
          - enum_for
          - to_enum
          - send
          - public_send
      - variable: USER_INPUT
        detection: ruby_lang_reflection_using_user_input_user_input
  - pattern: |
      $<METHOD>($<USER_INPUT>$<...>)$<...>
    filters:
      - variable: METHOD
        values:
          - method
          - instance_method
          - public_method
          - singleton_method
          - define_method
          - define_singleton_method
          - instance_variable_get
          - instance_variable_set
          - remove_instance_variable
          - enum_for
          - to_enum
          - send
          - public_send
      - variable: USER_INPUT
        detection: ruby_lang_reflection_using_user_input_user_input
  - pattern: |
      $<USER_INPUT>.to_proc
    filters:
      - variable: USER_INPUT
        detection: ruby_lang_reflection_using_user_input_user_input
  - pattern: |
      $<_>(&$<USER_INPUT>)
    filters:
      - variable: USER_INPUT
        detection: ruby_lang_reflection_using_user_input_user_input
  - pattern: |
      $<_>.$<_>(&$<USER_INPUT>)
    filters:
      - variable: USER_INPUT
        detection: ruby_lang_reflection_using_user_input_user_input
  - pattern: |
      $<USER_INPUT>.$<METHOD>
    filters:
      - variable: USER_INPUT
        detection: ruby_lang_reflection_using_user_input_user_input
      - variable: METHOD
        values:
          - constantize
          - safe_constantize
auxiliary:
  - id: ruby_lang_reflection_using_user_input_user_input
    patterns:
      - params
      - request
      - cookies
      - | # AWS lambda
        def $<_>($<!>event:, context:)
        end
trigger: presence
severity: high
metadata:
  description: "Use of reflection influenced by user input detected."
  remediation_message: |
    ## Description

    Applications should not look up or manipulate code using user-supplied data.

    ## Remediations

    ❌ Avoid using user input when using reflection:

    ```ruby
    method(params[:method])
    ```

    ✅ Use user input indirectly when using reflection:

    ```ruby
    method_name =
      case params[:action]
      when "option1"
        "method1"
      when "option2"
        "method2"
      end

    method(method_name)
    ```
    <!--
    ## Resources
    Coming soon.
    -->
  cwe_id:
    - 94
  id: ruby_lang_reflection_using_user_input
