type: "risk"
patterns:
  - |
    Net::HTTP.start($<_>, $<_>, $<_>, :verify_mode => OpenSSL::SSL::VERIFY_NONE)
  - |
    Net::HTTP.start($<_>, $<_>, $<_>, verify_mode: OpenSSL::SSL::VERIFY_NONE)
  - |
    $<_>.verify_mode = OpenSSL::SSL::VERIFY_NONE
languages:
  - ruby
detect_presence: true
trigger: "local"
severity:
  default: "medium"
metadata:
  description: "Do not disable SSL certificate verification."
  remediation_message: ""
  dsr_id: "DSR-2"
