type: "risk"
patterns:
  - |
    Net::HTTP.start(:verify_mode => OpenSSL::SSL::VERIFY_NONE)$<...>
  - |
    Net::HTTP.start(verify_mode: OpenSSL::SSL::VERIFY_NONE)$<...>
  - |
    Net::HTTP.start($<...>{ :verify_mode => OpenSSL::SSL::VERIFY_NONE })$<...>
  - |
    Net::HTTP.start($<...>{ verify_mode: OpenSSL::SSL::VERIFY_NONE })$<...>
  - |
    $<_>.verify_mode = OpenSSL::SSL::VERIFY_NONE
languages:
  - ruby
detect_presence: true
trigger: "local"
severity:
  default: "medium"
metadata:
  description: "Do not disable SSL certificate verification."
  remediation_message: ""
  dsr_id: "DSR-2"
  id: "ruby_lang_ssl_verification"
