type: "risk"
patterns:
  - pattern: |
      Digest::SHA1.hexidigest($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      Digest::MD5.hexdigest($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      OpenSSL::PKey::$<LIBRARY>.new($<_>, $<DATA_TYPE>)
    filters:
      - variable: LIBRARY
      - values:
          - DSA
          - RSA
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      RC4.new().encrypt($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      OpenSSL::PKey::RSA.new($<_>, $<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      OpenSSL::PKey::RSA.new().$<METHOD>($<DATA_TYPE>)
    filters:
      - variable: METHOD
        values:
          - private_decrypt
          - private_encrypt
          - public_decrypt
          - public_encrypt
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      OpenSSL::PKey::DSA.new($<_>, $<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      OpenSSL::PKey::$<LIBRARY>.new().$<METHOD>($<_>, $<DATA_TYPE>)
    filters:
      - variable: LIBRARY
        values:
          - DSA
          - RSA
      - variable: METHOD
        values:
          - export
          - to_pem
          - to_s
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      Crypt::Blowfish.new().$<METHOD>($<DATA_TYPE>)
    filters:
      - variable: METHOD
        values:
          - encrypt_pair
          - encrypt_string
          - encrypt_block
          - decrypt_pair
          - decrypt_string
          - decrypt_block
      - variable: DATA_TYPE
        detection: datatype
languages:
  - "ruby"
trigger: "local"
severity:
  default: "low"
  PII: "critical"
  PHI: "medium"
  PD: "high"
only_data_types:
  - "Unique Identifier"
metadata:
  description: "Force strong password encryption."
  remediation_message: ""
  dsr_id: "DSR-7"
  id: "ruby_lang_weak_password_encryption"
