type: "risk"
patterns:
  - pattern: |
      $<VAR>.$<METHOD>($<DATA_TYPE>)
    filters:
      - variable: VAR
        detection: rc4_init
      - variable: METHOD
        values:
          - encrypt
          - encrypt!
          - decrypt
      - variable: DATA_TYPE
        detection: datatype
languages:
  - "ruby"
auxiliary:
  - id: "rc4_init"
    type: "verifier"
    patterns:
      - |
        RC4.new()
    languages:
      - "ruby"
trigger: "local"
severity:
  default: "low"
  PII: "critical"
  PHI: "medium"
  PD: "high"
metadata:
  description: "Do not use weak encryption libraries."
  remediation_message: ""
  dsr_id: "DSR-7"
  id: "ruby_lang_weak_encryption"