type: "risk"
patterns:
  - |
    $<_> = Crypt::Blowfish.new()
  - |
    $<_> = OpenSSL::PKey::DSA.new()
  - |
    $<_> = OpenSSL::PKey::RSA.new()
  - |
    $<_> = RC4.new()
  - pattern: |
      $<_>.$<METHOD>()
    filters:
      - variable: METHOD
        values:
          - encrypt_pair
          - encrypt_string
          - encrypt_block
          - decrypt_pair
          - decrypt_string
          - decrypt_block
  - pattern: |
      $<_>.$<METHOD>()
    filters:
      - variable: METHOD
        values:
          - private_decrypt
          - private_encrypt
          - public_decrypt
          - public_encrypt
languages:
  - "ruby"
trigger: "local"
severity:
  default: "low"
  PII: "critical"
  PHI: "medium"
  PD: "high"
skip_data_types:
  - "Unique Identifier"
metadata:
  description: "Do not use weak encryption libraries."
  remediation_message: ""
  dsr_id: "DSR-7"