patterns:
  - pattern: |
      Digest::SHA1.hexidigest($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      Digest::MD5.hexdigest($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      $<VAR>.$<METHOD>($<DATA_TYPE>)
    filters:
      - variable: VAR
        detection: ruby_lang_weak_encryption_with_data_rc4_init
      - variable: METHOD
        values:
          - encrypt
          - encrypt!
          - decrypt
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      $<VAR>.$<METHOD>($<DATA_TYPE>)
    filters:
      - variable: VAR
        detection: ruby_lang_weak_encryption_with_data_openssl_rsa_init
      - variable: METHOD
        values:
          - private_decrypt
          - private_encrypt
          - public_decrypt
          - public_encrypt
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      $<VAR>.$<METHOD>($<_>, $<DATA_TYPE>)
    filters:
      - variable: VAR
        detection: ruby_lang_weak_encryption_with_data_openssl_rsa_init
      - variable: METHOD
        values:
          - export
          - to_pem
          - to_s
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      $<VAR>.$<METHOD>($<_>, $<DATA_TYPE>)
    filters:
      - variable: VAR
        detection: ruby_lang_weak_encryption_with_data_openssl_dsa_init
      - variable: METHOD
        values:
          - export
          - to_pem
          - to_s
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      $<VAR>.$<METHOD>($<DATA_TYPE>)
    filters:
      - variable: VAR
        detection: ruby_lang_weak_encryption_with_data_blowfish_init
      - variable: METHOD
        values:
          - encrypt_string
          - decrypt_string
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      $<VAR>.$<METHOD>($<_>, $<DATA_TYPE>)
    filters:
      - variable: VAR
        detection: ruby_lang_weak_encryption_with_data_blowfish_init
      - variable: METHOD
        values:
          - encrypt_pair
          - decrypt_pair
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      $<VAR>.$<METHOD> do
        $<DATA_TYPE>
      end
    filters:
      - variable: VAR
        detection: ruby_lang_weak_encryption_with_data_blowfish_init
      - variable: METHOD
        values:
          - encrypt_block
          - decrypt_block
      - variable: DATA_TYPE
        detection: datatype
languages:
  - ruby
auxiliary:
  - id: ruby_lang_weak_encryption_with_data_rc4_init
    patterns:
      - |
        RC4.new()
  - id: ruby_lang_weak_encryption_with_data_openssl_rsa_init
    patterns:
      - pattern: |
          OpenSSL::PKey::RSA.new()
        filters:
          - variable: LENGTH
            less_than: 2048
  - id: ruby_lang_weak_encryption_with_data_openssl_dsa_init
    patterns:
      - |
        OpenSSL::PKey::DSA.new()
  - id: ruby_lang_weak_encryption_with_data_blowfish_init
    patterns:
      - |
        Crypt::Blowfish.new()
trigger: local
severity:
  default: low
  PII: critical
  PHI: medium
  PD: high
metadata:
  description: "Sensitive data encrypted with a weak encryption library detected."
  remediation_message: |
    ## Description

    A weak encryption or hashing library can lead to data breaches and greater security risk. This rule checks if weak encryption techniques are used on sensitive data.

    ## Remediations
    According to [OWASP](https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/04-Testing_for_Weak_Encryption): MD5, RC4, DES, Blowfish, SHA1. 1024-bit RSA or DSA, 160-bit ECDSA (elliptic curves), 80/112-bit 2TDEA (two key triple DES) are considered as weak hash/encryption algorithms and therefor shouldn't be used.

    ❌ Avoid libraries and algorithms with known weaknesses:

    ```ruby
    Digest::SHA1.hexdigest 'weak password encryption'
    Crypt::Blowfish.new("weak password encryption")
    RC4.new("weak password encryption")
    OpenSSL::PKey::RSA.new 1024
    OpenSSL::PKey::DSA.new 1024
    Digest::MD5.hexdigest 'unsecure string'
    ```

    ✅ Instead, we recommend using bcrypt:

    ```ruby
    BCrypt::Password.create('iLOVEdogs123')
    ```

    ## Resources
    - [BCrypt Explained](https://dev.to/sylviapap/bcrypt-explained-4k5c)
  cwe_id:
    - 326
    - 331
  id: ruby_lang_weak_encryption_with_data
