patterns:
  - pattern: |
      class $<_>
        def $<BEFORE_BUGSNAG_NOTIFY>($<EVENT>)
          $EVENT.add_metadata($<...>$<DATA_TYPE>$<...>)
        end
      end
    filters:
      - variable: DATA_TYPE
        detection: datatype
      - variable: BEFORE_BUGSNAG_NOTIFY
        detection: before_bugsnag_notify
  - pattern: |
      Bugsnag.leave_breadcrumb($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      Bugsnag.notify($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      Bugsnag.notify($<_>) do |$<EVENT:identifier>|
        $<EVENT>.add_metadata($<...>$<DATA_TYPE>$<...>)
      end
languages:
  - ruby
trigger: local
severity:
  default: low
  PII: critical
  PHI: medium
  PD: high
skip_data_types:
  - "Unique Identifier"
auxiliary:
  - id: before_bugsnag_notify
    patterns:
      - |
        before_bugsnag_notify :$<_>
metadata:
  description: "Do not send sensitive data to Bugsnag."
  remediation_message: |
    ## Description
    Leaking sensitive data to third-party loggers is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to Bugsnag.

    ## Remediations

    When logging errors or events, ensure all sensitive data is removed.

    ## Resources
    - [Bugsnag Docs](https://)
    - [Log obfuscation](https://)
  dsr_id: DSR-1
  associated_recipe: Bugsnag
  id: ruby_third_parties_bugsnag
