patterns:
  - pattern: |
      $<VAR>.message_text = $<DATA_TYPE>
    filters:
      - variable: VAR
        detection: google_dataflow_message_text_classes
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      $<VAR>.description = $<DATA_TYPE>
    filters:
      - variable: VAR
        detection: google_dataflow_description_classes
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      $<VAR>.value = $<DATA_TYPE>
    filters:
      - variable: VAR
        detection: google_dataflow_value_classes
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      $<VAR>.create_job_from_template($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: VAR
        detection: google_dataflow_templates_service_client_init
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      $<VAR>.$<METHOD> = $<DATA_TYPE>
    filters:
      - variable: VAR
        detection: google_dataflow_template_metadata_init
      - variable: DATA_TYPE
        detection: datatype
      - variable: METHOD
        values:
          - description
          - name
  - pattern: |
      $<VAR>.metadata = $<...>$<DATA_TYPE>$<...>
    filters:
      - variable: VAR
        detection: google_dataflow_config
      - variable: DATA_TYPE
        detection: datatype
languages:
  - ruby
auxiliary:
  - id: google_dataflow_client_init
    patterns:
      - |
        Google::Cloud::Dataflow::$<_>::$<_>::Client.new
      - pattern: |
          Google::Cloud::Dataflow.$<METHOD>
        filters:
          - variable: METHOD
            values:
              - messages
              - templates_service
              - flex_templates_service
              - jobs
              - metrics
              - snapshots
  - id: google_dataflow_config
    patterns:
      - pattern: |
          $<VAR>.configure
        filters:
          - variable: VAR
            detection: google_dataflow_client_init
      - pattern: |
          $<VAR>.configure { |$<!>$<_:identifier>| }
        filters:
          - variable: VAR
            detection: google_dataflow_client_init
  - id: google_dataflow_message_text_classes
    patterns:
      - |
        Google::Cloud::Dataflow::$<_>::StructuredMessage.new
      - |
        Google::Cloud::Dataflow::$<_>::JobMessage.new
  - id: google_dataflow_snapshots_client_init
    patterns:
      - |
        Google::Cloud::Dataflow::$<_>::Snapshots::Client.new
      - |
        Google::Cloud::Dataflow.snapshots
  - id: google_dataflow_description_classes
    patterns:
      - |
        Google::Cloud::Dataflow::$<_>::SnapshotJobRequest.new
      - pattern: |
          $<VAR>.get_snapshot
        fitlers:
          - variable: VAR
            detection: google_dataflow_snapshots_client_init
  - id: google_dataflow_value_classes
    patterns:
      - |
        Google::Cloud::Dataflow::$<_>::JobMessage.new
      - |
        Google::Cloud::Dataflow::$<_>::CreateJobFromTemplateRequest::ParametersEntry.new
      - |
        Google::Cloud::Dataflow::$<_>::ParameterMetadata::CustomMetadataEntry.new
      - |
        Google::Cloud::Dataflow::$<_>::StructuredMessage::Parameter.new
  - id: google_dataflow_templates_service_client_init
    patterns:
      - |
        Google::Cloud::Dataflow::$<_>::TemplatesService::Client.new
      - |
        Google::Cloud::Dataflow.templates_service
  - id: google_dataflow_template_metadata_init
    patterns:
      - |
        Google::Cloud::Dataflow::$<_>::TemplateMetadata.new
trigger: local
skip_data_types:
  - "Unique Identifier"
metadata:
  description: "Sensitive data sent to Google Dataflow detected."
  remediation_message: |
    ## Description
    Leaking sensitive data to a third-party service is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to Google Dataflow.

    ## Remediations

    When sending data to third-party services, ensure all sensitive data is removed.

    ## Resources
    - [Google Dataflow Docs](https://cloud.google.com/ruby/docs/reference/google-cloud-dataflow/latest)
  cwe_id:
    - 201
  id: ruby_third_parties_google_dataflow
