type: "risk"
patterns:
  - pattern: |
      NewRelic::Agent.add_custom_attributes($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      NewRelic::Agent.add_custom_parameters($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      NewRelic::Agent.notice_error($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
languages:
  - ruby
trigger: "local"
severity:
  default: "low"
  PII: "critical"
  PHI: "medium"
  PD: "high"
skip_data_types:
  - "Unique Identifier"
metadata:
  description: "Do not send sensitive data to New Relic."
  remediation_message: ""
  dsr_id: "DSR-1"
  id: "ruby_third_parties_new_relic"
