patterns:
  - pattern: |
      NewRelic::Agent.add_custom_attributes($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      NewRelic::Agent.add_custom_parameters($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      NewRelic::Agent.notice_error($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
languages:
  - ruby
trigger: local
severity:
  default: low
  PII: critical
  PHI: medium
  PD: high
skip_data_types:
  - "Unique Identifier"
metadata:
  description: "Do not send sensitive data to New Relic."
  remediation_message: |
    ## Description
    Leaking sensitive data to third-party loggers is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to New Relic.

    ## Remediations

    When logging errors or events, ensure all sensitive data is removed.

    ## Resources
    - [New Relic Docs](https://docs.newrelic.com/)
    - [Log obfuscation](https://docs.newrelic.com/docs/logs/ui-data/obfuscation-ui/)
  dsr_id: DSR-1
  cwe_id:
    - 201
  associated_recipe: New Relic
  id: ruby_third_parties_new_relic
