patterns:
  - pattern: |
      $<_>.rollbar_context = $<DATA_TYPE>
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      Rollbar.$<METHOD>($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: METHOD
        values:
          - critical
          - error
          - debug
          - info
          - warning
          - scope
          - scope!
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      Rollbar.log($<_>, $<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      $<INSTANCE>.scope($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: INSTANCE
        detection: ruby_third_parties_rollbar_scope
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      Rollbar.scoped($<...>$<DATA_TYPE>$<...>)$<...>
    filters:
      - variable: DATA_TYPE
        detection: datatype
languages:
  - ruby
auxiliary:
  - id: ruby_third_parties_rollbar_scope
    patterns:
      - |
        Rollbar.scope()
trigger: local
severity:
  default: low
  PII: critical
  PHI: medium
  PD: high
skip_data_types:
  - "Unique Identifier"
metadata:
  description: "Sensitive data sent to Rollbar detected."
  remediation_message: |
    ## Description
    Leaking sensitive data to third-party loggers is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to Rollbar.

    ## Remediations

    When logging errors or events, ensure all sensitive data is removed.

    ## Resources
    - [Rollbar docs](https://docs.rollbar.com/docs/ruby)
    - [Scrubbing items](https://docs.rollbar.com/docs/ruby#section-scrubbing-items)
  dsr_id: DSR-1
  cwe_id:
    - 201
  associated_recipe: Rollbar
  id: ruby_third_parties_rollbar
