type: "risk"
patterns:
  - pattern: |
      Sentry::Breadcrumb.new($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      Sentry.init do |config|
        config.before_breadcrumb = lambda do |$<BREADCRUMB:identifier>, $<_:identifier>|
          $<BREADCRUMB>.message = $<DATA_TYPE>
        end
      end
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      Sentry.set_user($<DATA_TYPE>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
languages:
  - ruby
trigger: "local"
severity:
  default: "low"
  PII: "critical"
  PHI: "medium"
  PD: "high"
skip_data_types:
  - "Unique Identifier"
metadata:
  description: "Do not send sensitive data to Sentry."
  remediation_message: ""
  dsr_id: "DSR-1"
