type: "risk"
patterns:
  - pattern: |
      Sentry::Breadcrumb.new($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      Sentry.init do |$<CONFIG:identifier>|
        $<CONFIG>.before_breadcrumb = lambda do |$<BREADCRUMB:identifier>, $<_:identifier>|
          $<BREADCRUMB>.message = $<DATA_TYPE>
        end
      end
    filters:
      - variable: DATA_TYPE
        detection: datatype
  - pattern: |
      Sentry.set_user($<...>$<DATA_TYPE>$<...>)
    filters:
      - variable: DATA_TYPE
        detection: datatype
languages:
  - ruby
trigger: "local"
severity:
  default: "low"
  PII: "critical"
  PHI: "medium"
  PD: "high"
skip_data_types:
  - "Unique Identifier"
metadata:
  description: "Do not send sensitive data to Sentry."
  remediation_message: |
    ## Description
    Leaking sensitive data to third-party loggers is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to Sentry.

    ## Remediations

    When logging errors or events, ensure all sensitive data is removed.

    ## Resources
    - [Sentry Docs](https://docs.sentry.io/)
  dsr_id: "DSR-1"
  id: "ruby_third_parties_sentry"
